(function(g){var window=this;'use strict';var Lhb=function(a,b){return b?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},Mhb=function(a,b){var c=new g.VN;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.j=a.j;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;a.xtags&&(c.xtags=a.xtags);a.captionId&&(c.captionId=a.captionId);return c},Nhb=function(a,b){var c,d,e;
return g.Ga(function(f){if(1==f.j)return c=a+"|"+b,g.z(f,g.qD(),2);if(3!=f.j){d=f.B;if(!d)throw g.CC("gct");return g.z(f,g.HO(d),3)}e=f.B;return f.return(e.get("captions",c))})},Ohb=function(a,b,c){Nhb(a,b).then(function(d){d&&c(d.trackData,new g.VN(d.metadata))})},Rhb=function(a){if(!Phb.test(a))throw Error("'"+a+"' is not a valid hex color");
4==a.length&&(a=a.replace(Qhb,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},Shb=function(){return g.PB("yt-player-caption-display-settings")},N4=function(){this.segments=[]},Thb=function(a,b){var c=g.Qb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.Db(a.segments,c),g.Db(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.Mb(a.segments,c,0,b),g.Mb(a.segments,c+1,0,b)))},Uhb=function(a,b,c,d,e,f){g.G.call(this);
this.policy=a;this.player=b;this.ea=c;this.onLoadCallback=d;this.G=e;this.ma=f;this.D=new N4;this.K=-1;this.C=this.B=this.j=null;this.S=new g.br(this.VW,1E3,this);this.events=new g.KL(this);g.H(this,this.S);g.H(this,this.events);this.events.V(b,"SEEK_COMPLETE",this.lA);this.lA();this.VW()},Vhb=function(a){return a.j&&a.j.C?a.j.C+a.player.Jd()<a.player.getCurrentTime():!1},Whb=function(a,b){var c=g.hBa(b,a.policy,{}).jf(),d={format:"RAW",
withCredentials:!0};if(a.policy.Ca){d.method="POST";var e=b.nt(),f=(0,g.qW)([120,0]);e&&g.uO(e,g.xLa);d.postBody=f}a.G&&(d.responseType="arraybuffer");a.C=g.IA(c,d,3,100).then(function(h){a:{h=h.xhr;a.isDisposed();if(a.B){var l=!(a.G?h.response:h.responseText)||400<=h.status,m=g.qCa(h);if(m){h=g.hBa(a.B,a.policy,{});a.B.Qk(h,m);Whb(a,a.B);break a}if(l)a.player.Ba("capfail",{status:h.status});else if(a.player.oi().Hi("fcb_r"),m=a.B.ib[0].Qa,null!=a.onLoadCallback&&a.K!==m){l=a.B.ib[0];if(a.G)a.onLoadCallback(h.response,
1E3*(l.startTime+a.player.Jd()));else a.onLoadCallback(h.responseText,1E3*(l.startTime+a.player.Jd()));a.K=m}}a.B=null;a.C=null}}).xk(function(h){a.B=null;
a.C=null;var l;a.player.Ba("capfail",{status:null==(l=h.xhr)?void 0:l.status})});
a.B=b;Thb(a.D,a.B.ib[0].Qa)},O4=function(a,b){g.FR.call(this,b.W());
this.B=a;this.J=b;this.C=null;this.G=!1;this.K=g.IN(this.J.W())&&!this.B.isManifestless},Yhb=function(a,b){var c=[],d;
for(d in a.B.j)if(a.B.j.hasOwnProperty(d)){var e=a.B.j[d];if(g.ZLa(e,b||null)){var f=e.info.id,h=f,l="."+f,m="",n="",p="";if(e=e.info.captionTrack)f=e.languageCode,h=e.displayName,l=e.vssId,m=e.kind,a.J.W().N("html5_expose_xtags_through_caption_track")&&(n=e.xtags),p=e.id;else{e=f;var q=g.Kfb.get(e);null==q&&(q=Xhb[e]||Xhb[e.replace(/-/g,"_")],g.Kfb.set(e,q));h=q||h}c.push(new g.VN({id:d,languageCode:f,languageName:h,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m,xtags:n,captionId:p}))}}return c},
Zhb=function(a,b){return null!=b&&b in a.B.j?a.B.j[b]:null},$hb=function(a,b,c){var d=[],e;
for(e in a.B.j)if(a.B.j.hasOwnProperty(e)){var f=a.B.j[e];if(g.ZLa(f,c||null)){var h=f.info.captionTrack;h&&h.languageCode===b&&d.push(f)}}return d.length?d[0]:null},bib=function(){var a=void 0;
a=void 0===a?{}:a;var b="suggest_correction"in aib?aib.suggest_correction:"Edit caption";b=b||"";var c={},d;for(d in a){c={zD:c.zD};c.zD=d;var e=function(f){return function(){return String(a[f.zD])}}(c);
b=b.replace(new RegExp("\\$\\{"+c.zD+"\\}","gi"),e);b=b.replace(new RegExp("\\$"+c.zD,"gi"),e)}return b},P4=function(a,b,c,d,e,f,h,l,m,n){var p=n.isInline()&&n.N("web_imp_caption_window"),q={};
p&&(q.windowOpacity=.75);Object.assign(q,b);Object.assign(q,a.params);Object.assign(q,c);var t={};p&&(t.backgroundOpacity=0);Object.assign(t,b.We);a.params.We&&Object.assign(t,a.params.We);Object.assign(t,c.We);q.We=t;var u=1===q.Gi,y=[{I:"span",T:"captions-text",Y:{style:"word-wrap: normal; display: block;"}}],A,E,L;(l=l.rb("caption_edit_on_hover")&&(null==(A=n.getVideoData().getPlayerResponse())?void 0:null==(E=A.captions)?void 0:null==(L=E.playerCaptionsTracklistRenderer)?void 0:L.openTranscriptCommand))&&
y.unshift({I:"button",T:"caption-edit",Y:{tabindex:"0","aria-label":bib()},X:[{I:"svg",Y:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},X:[{I:"path",Y:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.W.call(this,{I:"div",T:"caption-window",Y:{id:"caption-window-"+a.id,dir:u?"rtl":"ltr",tabindex:"0",lang:q.lang},X:y});var I=
this;this.K=[];this.Ia=!1;this.B=a;this.Pa=this.Oa=null;this.playerWidth=f;this.playerHeight=h;this.S=null;this.maxWidth=.96*f;this.maxHeight=.96*h;this.j=q;this.Uc=c;this.Ca=b;this.D=this.Ha("captions-text");this.Ec=""!==this.D.style.getPropertyValue("box-decoration-break")||""!==this.D.style.getPropertyValue("-webkit-box-decoration-break");this.Va=cib(d,e,f,h);this.Tc=m;l&&(this.G=this.Ha("caption-edit"),this.V(this.G,"click",function(){I.Tc()}));
this.type=0;this.jb=this.Va*dib(t);this.Id=p;a=new g.dR(this.element,!0);g.H(this,a);a.subscribe("dragstart",this.o0,this);a.subscribe("dragmove",this.n0,this);a.subscribe("dragend",this.m0,this);this.tb=this.kb=this.Cb=this.Ib=0;a="";this.j.windowOpacity&&(a=Rhb(this.j.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.j.windowOpacity+")");b={"background-color":a,display:!1===this.j.isVisible?"none":"","text-align":eib[this.j.textAlign]};this.Ec&&(b["border-radius"]=a?this.jb/8+"px":"");(this.C=
2===this.B.params.Gi||3===this.B.params.Gi)&&fib(this,this.element);g.zo(this.element,b);switch(this.j.gm){case 0:case 1:case 2:g.jr(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.jr(this.element,"ytp-caption-window-bottom")}},fib=function(a,b){var c="vertical-rl";
1===a.j.aR&&(c="vertical-lr");g.Oe&&(c="vertical-lr"===c?"tb-lr":"tb-rl");g.zo(b,"-o-writing-mode",c);g.zo(b,"-webkit-writing-mode",c);g.zo(b,"writing-mode",c);g.zo(b,"text-orientation","upright");g.jr(b,"ytp-vertical-caption");3===a.B.params.Gi&&(g.zo(b,"text-orientation",""),g.zo(b,"transform","rotate(180deg)"))},dib=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},gib=function(a,b){var c={},d=b.background?b.background:a.j.We.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.j.We.backgroundOpacity;d=Rhb(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Ec&&(c["box-decoration-break"]="clone",c["border-radius"]=a.jb/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.Va*dib(b)+"px";d=1;e=b.color||a.j.We.color;if(b.color||null!=b.textOpacity)e=Rhb(e),d=null==b.textOpacity?a.j.We.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var h="rgba(204, 204, 204, "+d+")";b.UL&&(h=e=b.UL);var l=a.Va/16/2,m=Math.max(l,1),n=Math.max(2*l,1),p=Math.max(3*l,1),q=Math.max(5*l,1);d=[];switch(f){case 4:for(;p<=q;p+=l)d.push(n+"px "+n+"px "+p+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=p;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+h);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(p=0;5>p;p++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.WA()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.j.We.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.italic&&(c["font-style"]=
"italic");b.underline&&(c["text-decoration"]="underline");b.y5&&(c.visibility="hidden");1===b.kW&&a.C&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.KN||g.AC,3===a.B.params.Gi?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Zn||2===b.Zn||3===b.Zn||4===b.Zn||5===b.Zn)if(g.KN)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Zn){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},hib=function(a){a.S=g.$e("SPAN");
g.zo(a.S,{display:"block"});g.jr(a.S,"caption-visual-line");a.D.appendChild(a.S)},iib=function(a,b){var c=g.$e("SPAN");
g.zo(c,{display:"inline-block","white-space":"pre-wrap"});g.zo(c,gib(a,b));c.classList.add("ytp-caption-segment");a.S.appendChild(c);c.previousElementSibling&&(g.zo(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.zo(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},jib=function(a,b,c){a.Ia=a.Ia||!!c;
var d={};Object.assign(d,a.j.We);Object.assign(d,c||b.j);Object.assign(d,a.Uc.We);(c=!a.S)&&hib(a);for(var e=a.Oa&&a.Pa&&g.kd(d,a.Pa)?a.Oa:iib(a,d),f="string"===typeof b.text,h=f?b.text.split("\n"):[b.text],l=0;l<h.length;l++){var m=0<l||!b.append,n=h[l];m&&!c?(hib(a),e=iib(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.af(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.KN||!g.Bo(n.children[2],"text-emphasis")||(m=a.C?"padding-right":"padding-top",g.Bo(n.children[2],"text-emphasis-position")&&(m=
a.C?"padding-left":"padding-bottom"),g.Oc?g.zo(e,m,"1em"):g.zo(e,m,"0.5em")))}a.Pa=d;a.Oa=e;a.K.push(b)},cib=function(a,b,c,d){var e=b/360*16;
b>=a&&(a=640,d>1.3*c&&(a=480),e=c/a*16);return e},Q4=function(a,b,c,d){g.FR.call(this,a);
this.videoData=b;this.audioTrack=c;this.bb=d;this.D=b.nx},R4=function(a,b,c,d,e,f,h,l,m,n){P4.call(this,a,b,c,d,e,f,h,l,m,n);
this.type=1},S4=function(a,b,c,d,e,f,h,l,m,n){P4.call(this,a,b,c,d,e,f,h,l,m,n);
var p=this;this.type=2;this.ea=[];this.ra=this.qa=this.Za=0;this.Ja=NaN;this.Rb=0;this.Ic=null;this.eb=new g.br(this.o8,433,this);this.G&&(n.yb(this.G,this,167342),this.V(this.G,"click",function(){n.ub(p.G)}),a=new g.dR(this.element,!0),g.H(this,a),a.subscribe("hoverstart",function(){n.Ya(p.G,!0)},this));
g.jr(this.element,"ytp-caption-window-rollup");g.H(this,this.eb);g.zo(this.element,"overflow","hidden")},kib=function(a,b){if(!b)return"";
a.C&&1!==a.B.params.aR&&(b*=-1);return"translate"+(a.C?"X":"Y")+"("+b+"px)"},lib=function(a){a.ea=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.B.params.Ar,c=0,d=0,e=a.ea.length-1;c<b&&-1<e;){var f=a.ea[e];d+=a.C?f.offsetWidth:f.offsetHeight;c++;e--}a.ea.length<b&&(d*=b/a.ea.length);a.qa=d;b=Math;c=b.max;isNaN(a.Ja)&&((d=a.j.Hs)?(e=g.$e("SPAN"),g.of(e,"\u2013".repeat(d)),g.zo(e,gib(a,a.j.We)),a.D.appendChild(e),a.Ja=e.offsetWidth,a.D.removeChild(e)):a.Ja=0);d=a.D;a.ra=c.call(b,a.Ja,a.Rb,(a.C?d.offsetHeight:d.offsetWidth)+1)},mib=function(a,b){lib(a);
var c=a.ea.reduce(function(e,f){return(a.C?f.offsetWidth:f.offsetHeight)+e},0);
c=a.qa-c;if(c!==a.Za){var d=0<c&&0===a.Za;b||isNaN(c)||d||(g.jr(a.element,"ytp-rollup-mode"),g.cr(a.eb));g.zo(a.D,"transform",kib(a,c));a.Za=c}lib(a)},T4=function(a,b,c,d,e,f,h){f=void 0===f?!1:f;
h=void 0===h?null:h;g.IP.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.j=h},U4=function(a,b,c,d,e){g.IP.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.j=[]},nib=function(a){var b="_"+V4++;
return new U4(0,0x8000000000000,0,b,a)},pib=function(a,b,c,d,e,f,h){var l=f[0],m=h[l.getAttribute("p")];
if(1===m.eg){var n=f[1],p=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");p.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");h=h[p.getAttribute("p")];l=oib(l.textContent,n.textContent,p.textContent,f.textContent,h);return new T4(a,b,e,c,l,d,m)}switch(m.eg){case 9:case 10:m.Zn=1;break;case 11:m.Zn=2;break;case 12:m.Zn=3;break;case 13:m.Zn=4;break;case 14:m.Zn=5}return new T4(a,b,e,c,l.textContent||"",d,m)},oib=function(a,b,c,d,e){var f=g.WA(),h=
f?g.$e("DIV"):g.$e("RUBY"),l=g.$e("SPAN");
l.textContent=a;h.appendChild(l);a=f?g.$e("DIV"):g.$e("RP");a.textContent=b;h.appendChild(a);b=f?g.$e("DIV"):g.$e("RT");b.textContent=c;h.appendChild(b);c=e.eg;if(10===c||11===c||12===c||13===c||14===c)if(g.zo(b,"text-emphasis-style","filled circle"),g.zo(b,"text-emphasis-color","currentcolor"),g.zo(b,"webkit-text-emphasis","filled circle"),11===e.eg||13===e.eg)g.zo(b,"webkit-text-emphasis-position","under left"),g.zo(b,"text-emphasis-position","under left");c=!0;if(4===e.eg||7===e.eg||12===e.eg||
14===e.eg)g.zo(h,"ruby-position","over"),g.zo(h,"-webkit-ruby-position","before");else if(5===e.eg||6===e.eg||11===e.eg||13===e.eg)g.zo(h,"ruby-position","under"),g.zo(h,"-webkit-ruby-position","after"),c=!1;e=f?g.$e("DIV"):g.$e("RP");e.textContent=d;h.appendChild(e);f&&(d=c,g.zo(h,{display:"inline-block",position:"relative"}),f=h.firstElementChild.nextElementSibling,g.zo(f,"display","none"),f=f.nextElementSibling,g.zo(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.zo(h.lastElementChild,"display","none"),d?(g.zo(h,"padding-top","0.6em"),g.zo(f,"top","0")):(g.zo(h,"padding-bottom","0.6em"),g.zo(f,"bottom","0")));return h},W4=function(){g.G.apply(this,arguments)},X4=function(a){W4.call(this);
this.D=a;this.pens={};this.ma={};this.ea={};this.G="_"+V4++;this.S={};this.C=this.j=null;this.K=!0},Y4=function(a,b){a=a.getAttribute(b);
if(null!=a)return Number(a)},Z4=function(a,b){a=a.getAttribute(b);
if(null!=a)return"1"===a},$4=function(a,b){a=Y4(a,b);
return void 0!==a?a:null},b5=function(a,b){a=a.getAttribute(b);
if(null!=a)return a5.test(a),a},qib=function(a,b){var c={},d=b.getAttribute("ws");
Object.assign(c,d?a.ea[d]:a.D);a=$4(b,"mh");null!=a&&(c.Zz=a);a=$4(b,"ju");null!=a&&(c.textAlign=a);a=$4(b,"pd");null!=a&&(c.Gi=a);a=$4(b,"sd");null!=a&&(c.aR=a);a=b5(b,"wfc");null!=a&&(c.windowColor=a);b=Y4(b,"wfo");void 0!==b&&(c.windowOpacity=b/255);return c},rib=function(a,b){var c={},d=b.getAttribute("wp");
d&&Object.assign(c,a.ma[d]);a=$4(b,"ap");null!=a&&(c.gm=a);a=Y4(b,"cc");null!=a&&(c.Hs=a);a=Y4(b,"ah");null!=a&&(c.Yj=a);a=Y4(b,"rc");null!=a&&(c.Ar=a);b=Y4(b,"av");null!=b&&(c.ao=b);return c},sib=function(a,b,c,d){var e={};
Object.assign(e,rib(a,b));Object.assign(e,qib(a,b));d?g.kd(e,a.D)?(d=a.G,e=a.D):d="_"+V4++:d=b.getAttribute("id")||"_"+V4++;a=Y4(b,"t")+c;b=Y4(b,"d")||0x8000000000000;if(2===e.Gi||3===e.Gi)c=e.Ar,e.Ar=e.Hs,e.Hs=c;return new U4(a,b,0,d,e)},c5=function(a){W4.call(this);
this.K=a;this.j=new Map;this.D=new Map;this.G=new Map;this.C=new Map},d5=function(a){a=g.pe(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},tib=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.D.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.G.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.Ar=a);b=b.ccColCount;void 0!==b&&(f.Hs=b);if(2===f.Gi||3===f.Gi)b=f.Ar,f.Ar=f.Hs,f.Hs=b;return new U4(c,d,0,e,f)},vib=function(){this.C=this.time=this.mode=this.B=0;
this.D=new uib(this);this.G=new uib(this);this.j=[];this.clear()},xib=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Tu:a,
Ds:b,result:0};a=wib[a];b=wib[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.He()&&c.Ds===d;if(d)return{Tu:a,Ds:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Tu:a,Ds:b,result:2};return{Tu:a,Ds:b,result:3}},zib=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.C&&a.reset(),a.D.B.clear(),a.G.B.clear()):(a.C=0,yib(a.D,b,c,d))},Aib=function(a,b){a.j.sort(function(e,f){var h=e.time-f.time;
return 0===h?e.order-f.order:h});
for(var c=g.v(a.j),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?zib(a,d.sU,d.tU,b):1===d.type&&a.B&496&&yib(a.G,d.sU,d.tU,b);a.j.length=0},e5=function(){this.type=0},f5=function(){this.state=this.Ds=this.Tu=0},Bib=function(){this.timestamp=this.j=0},g5=function(a){this.D=a;
this.B=[];this.j=this.col=this.row=0;this.style=new e5;for(a=this.C=0;15>=a;a++){this.B[a]=[];for(var b=0;32>=b;b++)this.B[a][b]=new Bib}},h5=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.D.time+0,f="",h="",l=e,m=1;15>=m;++m){for(var n=!1,p=d?d:1;32>=p;++p){var q=a.B[m][p];
if(0!==q.j){0===c&&(c=m,d=p);n=String.fromCharCode(q.j);var t=q.timestamp;t<e&&(e=t);q.timestamp=l;h&&(f+=h,h="");f+=n;n=!0}if((0===q.j||32===p)&&n){h="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.D(c,d,e,l,f)}else for(d=c=0,f=e=a.D.time+0,h=1;15>=h;++h)for(l="",m=1;32>=m;++m)if(p=a.B[h][m],q=p.j,0!==q&&(0===c&&(c=h,d=m),n=String.fromCharCode(q),t=p.timestamp,t<=e&&(e=t),l+=n,p.reset()),32===m||0===q)l&&b.D(c,d,e,f,l),e=f,l="",d=c=0},Gib=function(a,b){switch(a){case 0:return Cib[(b&127)-32];
case 1:return Dib[b&15];case 2:return Eib[b&31];case 3:return Fib[b&31]}return 0},i5=function(a){return a.B[a.row][a.col]},j5=function(a,b,c){2<=b&&1<a.col&&(--a.col,i5(a).j=0);
var d=i5(a);d.timestamp=a.D.time+0;d.j=Gib(b,c);32>a.col&&a.col++},Hib=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var h=a.B[b+e][f],l=a.B[c+e][f];
h.j=l.j;h.timestamp=l.timestamp}},k5=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.B[b+d][e].reset()},Iib=function(a){a.row=0<a.j?a.j:1;
a.col=1;k5(a,0,15)},Jib=function(a){this.C=a;
this.G=0;this.style=new e5;this.K=new g5(this.C);this.S=new g5(this.C);this.text=new g5(this.C);this.B=this.K;this.D=this.S;this.j=this.B},Kib=function(a,b,c){var d=a.B,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.j||(h5(d,c),Iib(a.B),Iib(a.D),d.row=15,d.j=b,e=!0)}a.style.set(3);a.j=d;a.j.style=a.style;a.C.mode=1<<d.C;e?d.col=1:d.j!==b&&(d.j>b?(h5(d,c),k5(d,d.row-d.j,b)):d.row<b&&(b=d.j),d.j=b)},Lib=function(a){a.style.set(1);
a.j=a.D;a.j.j=0;a.j.style=a.style;a.C.mode=1<<a.j.C},Mib=function(a){a.style.set(4);
a.j=a.text;a.j.style=a.style;a.C.mode=1<<a.j.C},uib=function(a){this.j=a;
this.G=0;this.C=new Jib(this.j);this.K=new Jib(this.j);this.B=new f5;this.D=this.C},yib=function(a,b,c,d){a.B.update();
b=xib(b,c,a.B);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Tu;c=b.Ds;if(32<=e||!e)a.j.mode&a.j.B&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.D.j,b&96&&j5(a,0,b),c&96&&j5(a,0,c),0!==b&&0!==c&&3===a.style.type&&h5(a,d));else if(e&16)a:if(!a.B.matches(e,c)&&(b=a.B,b.Tu=e,b.Ds=c,b.state=2,b=e&8?a.K:a.C,a.D=b,a.j.mode=1<<(a.G<<2)+(b.G<<1)+(4===b.style.type?1:0),(a.j.mode|1<<(a.G<<2)+(b.G<<1)+(4!==b.style.type?1:0))&a.j.B))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.j;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.j&&(d=c.j,d===c.row))break;var f=1+c.row-c.j,h=1+d-c.j;Hib(c,h,f,c.j);b=f;e=c.j;h<f?(f=h+e-f,0<f&&(b+=f,e-=f)):(f=f+e-h,0<f&&(e-=f));k5(c,b,e)}}c.row=d;c.col=a+1}else switch(e&7){case 1:switch(c&112){case 32:j5(b.j,0,32);break a;case 48:57===c?(d=b.j,i5(d).j=0,32>d.col&&d.col++):j5(b.j,1,c&15)}break;case 2:c&32&&j5(b.j,2,c&31);break;case 3:c&32&&j5(b.j,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:Lib(b);
break;case 33:d=b.j;1<d.col&&(--d.col,i5(d).j=0);break;case 36:d=b.j;b=i5(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.B[a][c]===b){for(;32>=c;c++)d.B[a][c].reset();break}break;case 37:Kib(b,2,d);break;case 38:Kib(b,3,d);break;case 39:Kib(b,4,d);break;case 40:j5(b.j,0,32);break;case 41:b.style.set(2);b.j=b.B;b.j.j=0;b.j.style=b.style;b.C.mode=1<<b.j.C;break;case 42:d=b.text;d.j=15;d.style.set(4);Iib(d);Mib(b);break;case 43:Mib(b);break;case 44:a=b.B;switch(b.style.get()){case 1:case 2:case 3:h5(a,
d)}k5(a,0,15);break;case 45:b:{a=b.j;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.col=1;break b}case 3:}2>a.j&&(a.j=2,a.row<a.j&&(a.row=a.j));b=a.row-a.j+1;h5(a,d);Hib(a,b,b+1,a.j-1);k5(a,a.row,1)}break;case 46:k5(b.D,0,15);break;case 47:h5(b.B,d),b.D.updateTime(b.C.time+0),d=b.D,b.D=b.B,b.B=d,Lib(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.j,32<(d.col+=c&3)&&(d.col=32)}}},Nib=function(){},l5=function(a,b,c){this.trackData=a;
this.K=c;this.version=this.G=this.C=this.byteOffset=0;this.j=new DataView(this.trackData);this.B=[]},m5=function(a){var b=a.byteOffset;
a.byteOffset+=1;return a.j.getUint8(b)},n5=function(a){var b=a.byteOffset;
a.byteOffset+=4;return a.j.getUint32(b)},o5=function(a,b){W4.call(this);
this.C=a;this.D=b;this.track="CC3"===this.D.languageName?4:0;this.j=new vib;this.j.B=1<<this.track},Pib=function(a){if("string"===typeof a)return!1;
a=new l5(a,8,0);return Oib(a)},Oib=function(a){if(!(a.byteOffset<a.j.byteLength)||1380139777!==n5(a))return!1;
a.version=m5(a);if(1<a.version)return!1;m5(a);m5(a);m5(a);return!0},p5=function(){W4.call(this)},Qib=function(a,b,c,d,e,f,h,l,m){switch(h.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var n=0;n<h.childNodes.length;n++){var p=h.childNodes[n];if(3===p.nodeType)p=new T4(b,c,d,e.id,p.nodeValue,f||0<n,g.hd(l)?void 0:l),m.push(p),e.j.push(p);else{var q={};Object.assign(q,l);Qib(a,b,c,d,e,!0,p,q,m)}}},Rib=function(a){var b=a.split(":");
a=0;b=g.v(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},Sib=function(a,b,c,d){d=Object.assign({Zz:0},d);
return new U4(a,b,c,"_"+V4++,d)},q5=function(a,b){g.G.call(this);
this.J=a;this.Z=b;this.parser=null;this.j=this.J.iz()},Yib=function(a,b,c,d,e){d=d||0;
e=e||0;if(a.j&&b){var f=e,h=Tib(a,b,d),l=[];try{for(var m=g.v(h),n=m.next();!n.done;n=m.next()){var p=n.value,q=p.trackData,t=p.SQ;l="string"!==typeof q?l.concat(Uib(a,c,q,t,f)):"WEBVTT"===q.substring(0,6)?l.concat(Vib(a,q,t)):l.concat(Wib(a,c,q,t))}var u=l}catch(y){g.RF(y),a.clear(),u=[]}if(0!==u.length)return u}b=Xib(b);if(!b)return[];try{return"string"!==typeof b?Uib(a,c,b,d,e):"WEBVTT"===b.substring(0,6)?Vib(a,b,d):Wib(a,c,b,d)}catch(y){return g.RF(y),a.clear(),[]}},Xib=function(a){if("string"===
typeof a||Pib(a))return a;
var b=new DataView(a);if(8>=b.byteLength||1718909296!==b.getUint32(4))return"";b=g.bK(b,0,1835295092);if(!b||!b.size)return"";a=new Uint8Array(a,b.dataOffset,b.size-(b.dataOffset-b.offset));return g.QJ(a)},Tib=function(a,b,c){if("string"===typeof b||Pib(b))return[{trackData:b,
SQ:c}];var d=new DataView(b);if(8>=d.byteLength||1718909296!==d.getUint32(4))return[];var e=g.FAa(d);if(a.j&&e){var f=g.wAa(e),h=g.xAa(e);e=e.j;f&&e&&a.j.oF(e,f,h)}a=g.iK(d,1835295092);if(!a||!a.length||!a[0].size)return[];f=[];for(h=0;h<a.length;h++)e=a[h],e=new Uint8Array(b,e.dataOffset,e.size-(e.dataOffset-e.offset)),e=g.QJ(e),f.push({trackData:e,SQ:c+1E3*h});Zib(d,f,c);return f=f.filter(function(l){return!!l.trackData})},Zib=function(a,b,c){var d=g.bK(a,0,1836476516),e=9E4;
d&&(e=g.cK(d)||9E4);d=0;for(var f=g.iK(a,1836019558),h=0;h<f.length;h++){var l=f[h];h<b.length&&(l=g.bK(a,l.dataOffset,1953653094))&&(l=g.bK(a,l.dataOffset,1952867444))&&(l=g.CAa(l)/e*1E3,0===h&&(d=l),b[h].SQ=l-d+c||c*h*1E3)}},Uib=function(a,b,c,d,e){if(!Pib(c))throw Error("Invalid binary caption track data");
a.parser||(a.parser=new o5(e,b));return a.parser.B(c,d)},Vib=function(a,b,c){a.parser||(a.parser=new p5);
a=a.parser.B(b,c);.01>Math.random()&&g.SF(Error("Deprecated subtitles format in web player: WebVTT"));return a},Wib=function(a,b,c,d){if("{"===c[0])try{return a.parser||(a.parser=new c5($ib(b))),a.parser.B(c,d)}catch(f){return g.RF(f),[]}var e=g.bab(c);
if(!e||!e.firstChild)throw a=Error("Invalid caption track data"),a.params=c,a;if("timedtext"===e.firstChild.tagName){if(3===Number(e.firstChild.getAttribute("format")))return a.parser||(a.parser=new X4($ib(b),a.Z)),a.parser.B(e,d);a=Error("Unsupported subtitles format in web player (Format2)");a.params=c;throw a;}if("transcript"===e.firstChild.tagName)throw a=Error("Unsupported subtitles format in web player (Format1)"),a.params=c,a;a=Error("Invalid caption track data");a.params=c;throw a;},$ib=function(a){var b=
{};
if(a=g.YN(a))b.lang=a,g.Qbb.test(a)&&(b.Gi=1);return b},r5=function(a){g.CR.call(this,a);
var b=this;this.J=a;this.Z=this.J.W();this.videoData=this.J.getVideoData();this.Ib=this.J.qb();this.C={We:{}};this.G={We:{}};this.Ia=[];this.ra={};this.Za={};this.qa=!1;this.Ec=g.EP(this.videoData);this.kb=g.$La(this.videoData,this.J);this.Rb=!!this.videoData.captionTracks.length;this.Ic=!!this.videoData.Md;this.eb="3"===this.Z.controlsType;this.j=this.S=this.ma=this.Va=this.tb=null;this.jb=new q5(this.J,this.Z);this.B=null;this.Ja=new g.KL(this);this.K=new g.W({I:"div",T:"ytp-caption-window-container",
Y:{id:"ytp-caption-window-container"}});this.ea={top:0,right:0,bottom:0,left:0,width:1,height:1};var c=null,d=g.fs("yt-html5-player-modules::subtitlesModuleData");d&&(c=new g.Ur(d));this.storage=c;var e;this.Cb=!(null==(e=a.Af())||!e.hF());this.D=ajb(this);this.Ca=!this.D&&this.eb&&this.Cb&&this.kb;g.H(this,this.jb);this.D?this.Pa=this.Oa=null:(this.Oa=new g.$q(this.qR,void 0,this),g.H(this,this.Oa),this.Pa=new g.br(this.P9,2E3,this),g.H(this,this.Pa));g.H(this,this.Ja);g.jQ(this.player,this.K.element,
4);g.H(this,this.K);this.D||this.Ja.V(a,"resize",this.sR);(this.Wb=g.rN(this.Z)&&!g.xB()&&!this.J.isFullscreen()&&!this.D&&!this.Ca)&&this.Ja.V(a,"resize",this.y7);this.Ja.V(a,"onPlaybackAudioChange",this.Q6);this.Ja.V(a,g.JP("captions"),function(f){b.onCueRangeEnter(f)});
this.Ja.V(a,g.KP("captions"),function(f){b.onCueRangeExit(f)});
bjb(this,Shb()||{});this.player.Ua("onCaptionsModuleAvailable")},ejb=function(a){if(1===a.Z.Rb||1===a.videoData.nF||"alwayson"===g.mP(a.videoData,"yt:cc"))return!0;
if(a.videoData.captionTracks.length)var b=a.player.getAudioTrack().B;if(2===a.Z.Rb){if(g.GN(a.Z))var c=cjb(a);else if(a.storage)try{c=a.storage.get("module-enabled")}catch(e){a.storage.remove("module-enabled")}else c=null;if(null!=c)return!!c}c=Lhb(a.player.getAudioTrack(),g.GN(a.Z));var d=g.mP(a.videoData,"yt:cc");if(void 0===djb(a)){if("CAPTIONS_INITIAL_STATE_ON_RECOMMENDED"===c)return d?"on"===d:!0;if("CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED"===c)return"on"===d}else return"on"===d;return"ON"===
b||"on"===g.mP(a.videoData,"yt:cc")},s5=function(a,b){if(a.B&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
a=a.player.getAudioTrack();return!!a.j||"FORCED_ON"===a.B},djb=function(a){var b=void 0,c=g.WB(g.VB(),65);
if(g.GN(a.Z)&&null!=c){if(null!=cjb(a))return!1;b=!c}return b},fjb=function(a){return a.Z.N("html5_honor_caption_availabilities_in_audio_track")&&!a.kb},gjb=function(a){var b;
a.Ec?b=new Q4(a.Z,a.videoData,a.player.getAudioTrack(),a.player):a.kb?b=new O4(a.videoData.j,a.player):a.Rb?b=new g.GR(a.Z,a.videoData,a.player.getAudioTrack()):b=new g.LR(a.Z,a.videoData.Md,a.videoData.videoId,g.tIa(a.videoData),a.videoData.Im,a.videoData.eventId);return b},u5=function(a,b){if(a.j){if(a.S&&a.S.D)return a.S.D;
g.xP(a.videoData)&&(b=!0);b||(b=a.Ic?!1:a.Rb?!1:!0);b=b||hjb(a);b=g.DR(a.j.j,b);var c=null;if(g.GN(a.Z)){var d=a.J.isInline()?void 0:g.PB("yt-player-caption-sticky-language");for(var e=[d,a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.mP(a.videoData,"yt:cc_default_lang")],f=!1,h=0;h<e.length;h++){var l=e[h];if(l){f=!0;for(var m=0;m<b.length;m++)if(g.YN(b[m])===l)return b[m];m=l.split("-")[0];for(var n=0;n<b.length;n++)if(a.Z.N("html5_enable_same_language_id_matching")){if(g.YN(b[n]).split("-")[0]===
l.split("-")[0])return b[n]}else if(g.YN(b[n])===m)return b[n]}}if(f&&a.j&&(e=a.j.D,e.length))for(e=g.v(e),f=e.next();!f.done;f=e.next())if(f=f.value,f.languageCode===d){c=f;break}}else for(d=[a.videoData.captionsLanguagePreference,a.Z.captionsLanguagePreference,g.mP(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(f=0;f<b.length;f++)if(g.YN(b[f])===d[e])return b[f];d=null;a.S&&a.S.C&&(d=a.S.C);d||(d=b.find(function(p){return p.isDefault})||null);
d||(d=b[0]||t5(a));!d||!c||a.Z.N("html5_enable_same_language_id_matching")&&g.YN(d).split("-")[0]===c.languageCode.split("-")[0]||(d=Mhb(d,c));return d}return null},t5=function(a){return a.S&&a.S.j},v5=function(a){var b=t5(a);
return!!b&&a.B===b},ijb=function(a){g.DR(a.j.j,!0);
var b=Lhb(a.player.getAudioTrack(),g.GN(a.Z)),c;"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===b?c=u5(a,a.qa):"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===b&&s5(a)?c=t5(a):djb(a)||a.qa||ejb(a)?c=u5(a,a.qa):s5(a)&&(c=t5(a));if(a.D||a.Ca){var d=g.DR(a.j.j,!0);b=[];for(var e=0;e<d.length;e++){var f=d[e],h=g.$e("TRACK");h.setAttribute("kind","subtitles");h.setAttribute("label",g.WN(f));h.setAttribute("srclang",g.YN(f));h.setAttribute("id",f.toString());a.Ca||h.setAttribute("src",a.j.Gv(f,"vtt"));f===c&&h.setAttribute("default",
"1");b.push(h)}c=a.J.Af();c.aC(b);c=c.Db();a.Cb&&a.Ja.V(c.textTracks,"change",a.X8)}else!a.B&&c&&w5(a,c),a.player.Ua("onCaptionsTrackListChanged"),a.player.Ua("onApiChange")},jjb=function(a,b){var c=a.J.Af().Db().textTracks;
a=a.B.toString();for(var d=0;d<c.length;d++){var e=c[d];e.id===a&&(b?"showing"!==e.mode&&(e.mode="showing"):"showing"===e.mode&&(e.mode="disabled"))}},w5=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.qa=c,a.qa&&(g.GN(a.Z)?x5(a,!!b):y5(a,!!b)));a.B=b;s5(a)&&(a.B=t5(a));var d;kjb(a,null!=(d=a.B)?d:void 0);a.load()},mjb=function(a,b){if(b instanceof U4){var c=a.ra[b.id];
c&&c.B!==b&&(c.dispose(),delete a.ra[b.id],c=null);c||(c=ljb(a,b))&&(a.ra[b.id]=c)}else c=b.windowId,a.Za[c]||(a.Za[c]=[]),a.Za[c].push(b)},ljb=function(a,b){var c=njb(a);
if(!c)return null;var d=a.B?g.YN(a.B):null;d&&g.Qbb.test(d)&&(b.params.Gi=1);var e=a.Ib.getPlayerSize();d=e.height*a.ea.height;e=e.width*a.ea.width;"google-live"!==a.Z.playerStyle||a.C.isDefault||Object.assign(b.params,a.C);switch(null!=b.params.Zz?b.params.Zz:1<b.j.length?1:0){case 1:return new R4(b,a.C,a.G,c.width,c.height,e,d,a.Z.experiments,a.qK.bind(a),a.J);case 2:return new S4(b,a.C,a.G,c.width,c.height,e,d,a.Z.experiments,a.qK.bind(a),a.J);default:return new P4(b,a.C,a.G,c.width,c.height,e,
d,a.Z.experiments,a.qK.bind(a),a.J)}},bjb=function(a,b,c){c=void 0===c?!1:c;
var d=z5.We;a.C={};Object.assign(a.C,z5);a.C.We={};Object.assign(a.C.We,d);a.G={We:{}};var e=b.backgroundOverride?a.G:a.C,f=b.background||d.background;a5.test(f);e.We.background=f;e=b.colorOverride?a.G:a.C;f=b.color||d.color;a5.test(f);e.We.color=f;e=b.windowColorOverride?a.G:a.C;f=b.windowColor||z5.windowColor;a5.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.G:a.C;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.We.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.G:a.C;f=b.fontSizeIncrement;
null==f&&(f=d.fontSizeIncrement);e.We.fontSizeIncrement=f;f=b.fontStyleOverride?a.G:a.C;e=b.fontStyle;null==e&&(e=d.bold&&d.italic?3:d.bold?1:d.italic?2:0);f=f.We;switch(e){case 1:f.bold=!0;delete f.italic;break;case 2:delete f.bold;f.italic=!0;break;case 3:f.bold=!0;f.italic=!0;break;default:delete f.bold,delete f.italic}e=b.textOpacityOverride?a.G:a.C;f=b.textOpacity;null==f&&(f=d.textOpacity);e.We.textOpacity=f;e=b.windowOpacityOverride?a.G:a.C;f=b.windowOpacity;null==f&&(f=z5.windowOpacity);e.windowOpacity=
f;e=b.charEdgeStyleOverride?a.G:a.C;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.We.charEdgeStyle=f;e=b.fontFamilyOverride?a.G:a.C;f=b.fontFamily;null==f&&(f=d.fontFamily);e.We.fontFamily=f;a.loaded&&a.sR();c&&g.OB("yt-player-caption-display-settings",b,2592E3)},pjb=function(a,b,c){b&&!a.ma?(b=nib({Gi:0,
lang:"en"}),a.ma=[b,new T4(b.start,b.end-b.start,0,b.id,null!=c?c:"Captions look like this")],a.player.yf(a.ma)):!b&&a.ma&&(ojb(a,a.ma),a.ma=null)},ojb=function(a,b){a.player.Op(b);
b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.Eb(a.Ia,c.value);g.ar(a.Oa)},kjb=function(a,b){a.Z.N("html5_modify_caption_vss_logging")&&(a.videoData.CB=b)},njb=function(a){var b=a.Ib.getVideoContentRect(!0).height,c=a.Ib.getVideoContentRect(!0).width;
if(!b||!c)return null;b*=a.ea.height;c*=a.ea.width;return{width:c,height:b}},y5=function(a,b){if(a.storage)try{a.storage.set("module-enabled",b)}catch(c){}},x5=function(a,b){a.J.isInline()||g.OB("yt-player-sticky-caption",b,2592E3)},cjb=function(a){if(!a.J.isInline())return g.PB("yt-player-sticky-caption")},ajb=function(a){var b,c=!(null==(b=a.J.Af())||!b.gF());
return a.eb&&c&&!a.kb},hjb=function(a){return a.Z.N("web_deprecate_always_includes_asr_setting")&&g.GN(a.Z)?!0:!!g.WB(g.VB(),66)};
g.HU.prototype.MC=g.ba(41,function(a){var b=2;this.Ca.has(a)?b=0:g.cSa(this,a)&&(b=1);return b});
g.eX.prototype.MC=g.ba(40,function(a){return this.md.MC(a)});
g.HU.prototype.oF=g.ba(39,function(a,b,c){this.Va.set(a,{Ls:b,jy:c})});
g.eX.prototype.oF=g.ba(38,function(a,b,c){this.md.oF(a,b,c)});
g.FR.prototype.PP=g.ba(31,function(){return!1});
g.FR.prototype.Jt=g.ba(30,function(){});
g.GR.prototype.Jt=g.ba(29,function(a,b,c){var d=this;this.isDisposed();b=this.Gv(a,b);this.Vr();this.B=g.EA(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.LR.prototype.Jt=g.ba(28,function(a,b,c){var d=this;this.isDisposed();b=this.Gv(a,b);this.Vr();this.B=g.EA(b,{format:"RAW",onSuccess:function(e){d.B=null;c(e.responseText,a)},
withCredentials:!0})});
g.mR.prototype.Cy=g.ba(27,function(){for(var a=g.Ke(document,"track",void 0,this.j),b=0;b<a.length;b++)g.ef(a[b])});
g.uU.prototype.Cy=g.ba(26,function(){this.mediaElement.Cy()});
g.mR.prototype.hF=g.ba(25,function(){return!(!this.j.textTracks||!this.j.textTracks.addEventListener)});
g.uU.prototype.hF=g.ba(24,function(){return this.mediaElement.hF()});
g.mR.prototype.gF=g.ba(23,function(){return!!this.j.textTracks});
g.uU.prototype.gF=g.ba(22,function(){return this.mediaElement.gF()});
g.mR.prototype.aC=g.ba(21,function(a){for(var b=0;b<a.length;b++)this.j.appendChild(a[b])});
g.uU.prototype.aC=g.ba(20,function(a){this.mediaElement.aC(a)});
g.XW.prototype.aD=g.ba(10,function(){return this.ma});
g.kY.prototype.aD=g.ba(9,function(){var a;return(null==(a=g.RP(this))?void 0:a.iz())||null});
g.bQ.prototype.iz=g.ba(8,function(){return this.app.aD()});
g.YX.prototype.iz=g.ba(7,function(){var a;return(null==(a=this.Da)?void 0:a.aD())||null});
g.HJ.prototype.qH=g.ba(3,function(a){return(a=this.Xm(a))?a.j:0});
g.OBa.prototype.qH=g.ba(2,function(){return 0});
var Qhb=/#(.)(.)(.)/,Phb=/^#(?:[0-9a-f]{3}){1,2}$/i,Xhb={aa:"Afar",ab:"Abkhazian",ace:"Achinese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",chg:"Chagatai",
chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",ckb_Arab:"Central Kurdish (Arabic)",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",
li:"Limburgish",lkt:"Lakota",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaq",
min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",
nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",
pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",
sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",
sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",
ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",
ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vi:"Vietnamese",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",
za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};N4.prototype.contains=function(a){a=g.Qb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
N4.prototype.length=function(){return this.segments.length/2};
g.x(Uhb,g.G);g.k=Uhb.prototype;g.k.ya=function(){g.G.prototype.ya.call(this);this.C&&this.C.cancel()};
g.k.lA=function(){this.seekTo(this.player.getCurrentTime())};
g.k.seekTo=function(a){a-=this.player.Jd();var b=this.j;this.j=g.xb(this.ea.Bq(a).ib);b!==this.j&&this.ma&&this.ma()};
g.k.reset=function(){this.D=new N4;this.K=-1;this.C&&(this.C.cancel(),this.C=null)};
g.k.VW=function(){this.isDisposed();var a;if(a=null!=this.j)a=this.j,a=a.j.us(a);if(a&&!this.C&&!(this.j&&30<this.j.startTime-this.player.getCurrentTime())){a=this.j;a=a.j.MB(a);var b=a.ib[0],c;if(null==(c=this.player.getVideoData())?0:c.enableServerStitchedDai)if(c=this.player.iz()){var d=b.j.info.id,e=b.Qa,f=a.ib[0].D;if(this.policy.Ca){if(c=c.nt(f,e,d,3))a.D=c}else if(d=c.Zy(f,e,d,3))if(c=c.MC(e),0===c)d&&(a.j=new g.BJ(d));else if(2===c){this.S.start();Vhb(this)&&this.seekTo(this.player.getCurrentTime());
return}}(this.policy.WB?b.j.index.tp(b.Qa):a.ib[0].duration)?(this.D.contains(a.ib[0].Qa)||Whb(this,a),this.j=g.xb(a.ib)):Vhb(this)&&this.seekTo(this.player.getCurrentTime())}this.S.start()};
g.x(O4,g.FR);g.k=O4.prototype;g.k.Jt=function(a,b,c){var d=this;this.Vr();b=Zhb(this,a.getId());b||(b=a.languageCode,b=this.B.isManifestless?$hb(this,b,"386"):$hb(this,b));if(b){var e=1E3*(b.index.qH(b.index.hn())-b.index.getStartTime(b.index.hn())),f=new g.WLa(this.Z);this.C=new Uhb(f,this.J,b,function(h,l){c(h,a,l,e)},this.K||g.uL(b.info),function(){d.C&&d.C.reset();
d.G=!0})}};
g.k.PP=function(){var a=this.G;this.G=!1;return a};
g.k.Oz=function(a){var b=this.K?[new g.VN({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.VN({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:this.B.isManifestless?Yhb(this,"386"):Yhb(this);b=g.v(b);for(var c=b.next();!c.done;c=b.next())g.ER(this.j,c.value);a()};
g.k.Vr=function(){this.C&&(this.C.dispose(),this.C=null)};
g.k.Gv=function(){return""};
var a5=/^#(?:[0-9a-f]{3}){1,2}$/i,aib=window.yt&&window.yt.msgs_||window.ytcfg&&window.ytcfg.msgs||{};g.Qa("yt.msgs_",aib);var eib=["left","right","center","justify"];g.x(P4,g.W);g.k=P4.prototype;g.k.o0=function(a,b){this.kb=a;this.tb=b;var c=g.Io(this.element,this.element.parentElement);this.Ib=a-c.x;this.Cb=b-c.y};
g.k.n0=function(a,b){if(a!==this.kb||b!==this.tb){g.ir(this.element,"ytp-dragging")||g.jr(this.element,"ytp-dragging");var c=g.Ko(this.element);a=a-this.Ib-.02*this.playerWidth;var d=b-this.Cb-.02*this.playerHeight,e=(a+c.width/2)/this.maxWidth*3;e=Math.floor(g.pe(e,0,2));var f=(d+c.height/2)/this.maxHeight*3;f=Math.floor(g.pe(f,0,2));b=e+3*f;a=(a+e/2*c.width)/this.maxWidth;a=100*g.pe(a,0,1);c=(d+f/2*c.height)/this.maxHeight;c=100*g.pe(c,0,1);this.B.params.gm=b;this.B.params.ao=c;this.B.params.Yj=
a;this.B.params.isDefault=!1;this.j.gm=b;this.j.ao=c;this.j.Yj=a;this.j.isDefault=!1;this.Ca.gm=b;this.Ca.ao=c;this.Ca.Yj=a;this.Ca.isDefault=!1;this.OY()}};
g.k.m0=function(){g.lr(this.element,"ytp-dragging")};
g.k.OY=function(){this.XA(this.K)};
g.k.getType=function(){return this.type};
g.k.XA=function(a){var b=this.Id?0:Math.min(this.oV(),this.maxWidth),c=this.nV(),d="";3===this.B.params.Gi&&(d="rotate(180deg)");g.zo(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.CL(a);d={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.j.Yj+2,f=this.j.gm;switch(f){case 0:case 3:case 6:(b=this.j.We.fontSizeIncrement)&&0<b&&2!==this.j.Gi&&
3!==this.j.Gi&&(e=Math.max(e/(1+2*b),2));d.left=e+"%";break;case 1:case 4:case 7:d.left=e+"%";e=this.D.offsetWidth;b||e?(b=b||e+1,d.width=b+"px",d["margin-left"]=b/-2+"px"):d.transform+=" translateX(-50%)";break;case 2:case 5:case 8:d.right=100-e+"%"}b=.96*this.j.ao+2;switch(f){case 0:case 1:case 2:d.top=b+"%";break;case 3:case 4:case 5:d.top=b+"%";(c=c||this.element.clientHeight)?(d.height=c+"px",d["margin-top"]=c/-2+"px"):d.transform+=" translateY(-50%)";break;case 6:case 7:case 8:d.bottom=100-
b+"%"}g.zo(this.element,d);if(this.G){c=this.D.offsetHeight;d=1;for(f=0;f<a.length;f++)b=a[f],"string"===typeof b.text&&(d+=b.text.split("\n").length-1,b.append||0===f||d++);c/=d;this.G.style.height=c+"px";this.G.style.width=c+"px";this.element.style.paddingLeft=c+5+"px";this.element.style.paddingRight=c+5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-c-5;c=Number(this.element.style.marginRight.replace("px",""))-c-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=
c+"px"}};
g.k.CL=function(a){var b;for(b=0;b<a.length&&a[b]===this.K[b];b++);if(this.Ia||this.K.length>b)b=0,this.Ia=!1,this.K=[],this.S=this.Pa=this.Oa=null,g.cf(this.D);for(;b<a.length;b++)jib(this,a[b])};
g.k.oV=function(){return 0};
g.k.nV=function(){return 0};
g.k.toString=function(){return g.W.prototype.toString.call(this)};g.x(Q4,g.FR);Q4.prototype.Jt=function(a,b,c){Ohb(this.videoData.videoId,a.vssId,c)};
Q4.prototype.Oz=function(a){if(this.audioTrack)for(var b=g.v(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())g.ER(this.j,c.value);a()};g.x(R4,P4);R4.prototype.CL=function(a){var b=this.B.j;P4.prototype.CL.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.j===e)var d=f;else{d={};Object.assign(d,c.j);Object.assign(d,qjb);var e=c.j;var f=d}jib(this,c,d)}};
var qjb={y5:!0};g.x(S4,P4);g.k=S4.prototype;g.k.OY=function(){g.dr(this.eb)};
g.k.o8=function(){g.lr(this.element,"ytp-rollup-mode");this.XA(this.Ic,!0)};
g.k.nV=function(){return this.C?this.ra:this.qa};
g.k.oV=function(){return this.C?this.qa:this.ra};
g.k.XA=function(a,b){this.Ic=a;if(this.B.params.Ar){for(var c=0,d=0;d<this.K.length&&c<a.length;d++)this.K[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.K.concat(a.slice(c)));this.Rb=this.ra;this.qa=this.ra=0;P4.prototype.XA.call(this,a);mib(this,b)}P4.prototype.XA.call(this,a)};g.x(T4,g.IP);T4.prototype.toString=function(){return g.IP.prototype.toString.call(this)};g.x(U4,g.IP);U4.prototype.toString=function(){return g.IP.prototype.toString.call(this)};
var V4=0;g.x(W4,g.G);W4.prototype.B=function(){return[]};
W4.prototype.reset=function(){};g.x(X4,W4);X4.prototype.reset=function(){this.S={};this.C=this.j=null;this.K=!0};
X4.prototype.B=function(a,b){a=a.firstChild;a.getAttribute("format");b=b||0;Number.isFinite(b);a=Array.from(a.childNodes);a=g.v(a);for(var c=a.next();!c.done;c=a.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "head":var d=c;break;case "body":var e=c}if(d)for(d=Array.from(d.childNodes),d=g.v(d),a=d.next();!a.done;a=d.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "pen":c=a.getAttribute("id");var f=this.pens,h={},l=a.getAttribute("p");l&&Object.assign(h,this.pens[l]);l=Z4(a,"b");
null!=l&&(h.bold=l);l=Z4(a,"i");null!=l&&(h.italic=l);l=Z4(a,"u");null!=l&&(h.underline=l);l=$4(a,"et");null!=l&&(h.charEdgeStyle=l);l=$4(a,"of");null!=l&&(h.offset=l);l=b5(a,"bc");null!=l&&(h.background=l);l=b5(a,"ec");null!=l&&(h.UL=l);l=b5(a,"fc");null!=l&&(h.color=l);l=$4(a,"fs");null!=l&&0!==l&&(h.fontFamily=l);l=Y4(a,"sz");void 0!==l&&(h.fontSizeIncrement=l/100-1);l=Y4(a,"bo");void 0!==l&&(h.backgroundOpacity=l/255);l=Y4(a,"fo");void 0!==l&&(h.textOpacity=l/255);l=$4(a,"rb");null!=l&&10!==l&&
0!==l&&(h.eg=10<l?l-1:l);a=$4(a,"hg");null!=a&&(h.kW=a);f[c]=h;break;case "ws":c=a.getAttribute("id");this.ea[c]=qib(this,a);break;case "wp":c=a.getAttribute("id"),this.ma[c]=rib(this,a)}if(e){d=[];e=Array.from(e.childNodes);e=g.v(e);for(a=e.next();!a.done;a=e.next())if(a=a.value,1===a.nodeType)switch(a.tagName){case "w":this.j=sib(this,a,b,!1);(a=this.S[this.j.id])&&a.end>this.j.start&&(a.end=this.j.start);this.S[this.j.id]=this.j;d.push(this.j);break;case "p":l=b;c=[];f=a.getAttribute("w")||this.G;
h=!!Z4(a,"a");l=(Y4(a,"t")||0)+l;var m=Y4(a,"d")||5E3;h||(!this.K&&this.C&&this.C.windowId===f&&this.C.end>l&&(this.C.end=l),this.C&&"\n"===this.C.text&&(this.C.text=""));var n=h?6:5,p=a.getAttribute("p");p=p?this.pens[p]:null;var q=Array.from(a.childNodes);q.length&&(this.K=null!=a.getAttribute("d"));for(var t=0;t<q.length;t++){var u=q[t],y=void 0;0<t&&(h=!0);var A=void 0;1===u.nodeType&&(A=u);if(A&&"s"===A.tagName){if((u=(u=A.getAttribute("p"))?this.pens[u]:null)&&u.eg&&(1===u.eg?(u=q.slice(t,t+
4),4===u.length&&(y=pib(l,m,f,h,n,u,this.pens),t+=3)):y=pib(l,m,f,h,n,[A],this.pens)),!y){var E=A;y=l;A=m;u=f;var L=h,I=n,F=E.textContent?E.textContent:"",S=E.getAttribute("p");S=S?this.pens[S]:null;E=Y4(E,"t")||0;y=new T4(y+E,A-E,I,u,F,L,S)}}else y=new T4(l,m,n,f,u.textContent||"",h,p);c.push(y);this.C=y}if(0<c.length)for(c[0].windowId===this.G&&(this.j=sib(this,a,b,!0),d.push(this.j)),a=g.v(c),c=a.next();!c.done;c=a.next())c=c.value,c.windowId=this.j.id,this.j.j.push(c),d.push(c)}b=d}else b=[];
return b};var rjb=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.x(c5,W4);c5.prototype.reset=function(){this.C.clear()};
c5.prototype.B=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens){a=0;for(var d=g.v(c.pens),e=d.next();!e.done;e=d.next()){e=e.value;var f={},h=e.pParentId;h&&Object.assign(f,this.j.get(h));e.bAttr&&(f.bold=!0);e.iAttr&&(f.italic=!0);e.uAttr&&(f.underline=!0);h=e.ofOffset;null!=h&&(f.offset=h);void 0!==e.szPenSize&&(f.fontSizeIncrement=e.szPenSize/100-1);h=e.etEdgeType;null!=h&&(f.charEdgeStyle=h);void 0!==e.ecEdgeColor&&(f.UL=d5(e.ecEdgeColor));h=e.fsFontStyle;null!=h&&0!==h&&(f.fontFamily=
h);void 0!==e.fcForeColor&&(f.color=d5(e.fcForeColor));void 0!==e.foForeAlpha&&(f.textOpacity=e.foForeAlpha/255);void 0!==e.bcBackColor&&(f.background=d5(e.bcBackColor));void 0!==e.boBackAlpha&&(f.backgroundOpacity=e.boBackAlpha/255);(h=e.rbRuby)&&10!==h&&(f.eg=10<h?h-1:h,f.Zn=rjb.get(f.eg));e.hgHorizGroup&&(f.kW=e.hgHorizGroup);this.j.set(a++,f)}}if(c.wsWinStyles)for(a=0,d=g.v(c.wsWinStyles),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wsParentId)?Object.assign(f,this.G.get(h)):Object.assign(f,
this.K),void 0!==e.mhModeHint&&(f.Zz=e.mhModeHint),void 0!==e.juJustifCode&&(f.textAlign=e.juJustifCode),void 0!==e.pdPrintDir&&(f.Gi=e.pdPrintDir),void 0!==e.sdScrollDir&&(f.aR=e.sdScrollDir),void 0!==e.wfcWinFillColor&&(f.windowColor=d5(e.wfcWinFillColor)),void 0!==e.wfoWinFillAlpha&&(f.windowOpacity=e.wfoWinFillAlpha/255),this.G.set(a++,f);if(c.wpWinPositions)for(a=0,d=g.v(c.wpWinPositions),e=d.next();!e.done;e=d.next())e=e.value,f={},(h=e.wpParentId)&&Object.assign(f,this.D.get(h)),void 0!==e.ahHorPos&&
(f.Yj=e.ahHorPos),void 0!==e.apPoint&&(f.gm=e.apPoint),void 0!==e.avVerPos&&(f.ao=e.avVerPos),void 0!==e.ccCols&&(f.Hs=e.ccCols),void 0!==e.rcRows&&(f.Ar=e.rcRows),this.D.set(a++,f);if(c.events){a=[];c=g.v(c.events);for(d=c.next();!d.done;d=c.next()){var l=d.value;d=(l.tStartMs||0)+b;e=l.dDurationMs||0;if(l.id)f=String(l.id),d=tib(this,l,d,e,f),a.push(d),this.C.set(f,d);else{l.wWinId?f=l.wWinId.toString():(f="_"+V4++,h=tib(this,l,d,e,f),a.push(h),this.C.set(f,h));0===e&&(e=5E3);h=this.C.get(f);var m=
!!l.aAppend,n=m?6:5,p=l.segs,q=null;l.pPenId&&(q=this.j.get(l.pPenId));for(l=0;l<p.length;l++){var t=p[l],u=t.utf8;if(u){var y=t.tOffsetMs||0,A=null;t.pPenId&&(A=this.j.get(t.pPenId));if(2===(null!=h.params.Zz?h.params.Zz:1<h.j.length?1:0)&&m&&"\n"===u)continue;if(t=A&&1===A.eg)if(t=l,t+3>=p.length||!p[t+1].pPenId||!p[t+2].pPenId||!p[t+3].pPenId)t=!1;else{var E=p[t+1].pPenId;(E=this.j.get(E))&&E.eg&&2===E.eg?(E=p[t+2].pPenId,E=this.j.get(E),!E||!E.eg||3>E.eg?t=!1:(E=p[t+3].pPenId,t=(E=this.j.get(E))&&
E.eg&&2===E.eg?!0:!1)):t=!1}if(t){y=p[l+1].utf8;t=p[l+3].utf8;E=p[l+2].utf8;var L=this.j.get(p[l+2].pPenId);u=oib(u,y,E,t,L);m=new T4(d,e,n,f,u,m,A);l+=3}else m=new T4(d+y,e-y,n,h.id,u,m,A||q);m&&(a.push(m),h.j.push(m))}m=!0}}}b=a}else b=[];return b};vib.prototype.clear=function(){this.C=this.time=this.mode=0;this.j=[];this.reset()};
vib.prototype.reset=function(){this.mode=0;this.D.reset(0);this.G.reset(1)};
var wib=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];e5.prototype.set=function(a){this.type=a};
e5.prototype.get=function(){return this.type};
f5.prototype.clear=function(){this.state=0};
f5.prototype.update=function(){this.state=2===this.state?1:0};
f5.prototype.He=function(){return 0!==this.state};
f5.prototype.matches=function(a,b){return this.He()&&a===this.Tu&&b===this.Ds};
Bib.prototype.reset=function(){this.timestamp=this.j=0};
g5.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.B[b][c].timestamp=a};
g5.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.B[b][c];a=0===d.j?a+"_":a+String.fromCharCode(d.j)}a+="\n"}return a};
g5.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.B[b][c].reset();this.C=a;this.j=0;this.col=this.row=1};
var Cib=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],Dib=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],Eib=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],Fib=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];Jib.prototype.reset=function(a,b){this.G=b;this.style.set(2);this.B=this.K;this.D=this.S;this.j=this.B;var c=(a<<2)+(b<<1);this.K.reset(c);this.S.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
uib.prototype.reset=function(a){this.G=a;this.B.clear();this.D=this.C;this.C.reset(a,0);this.K.reset(a,1)};Nib.prototype.D=function(){};g.x(l5,Nib);l5.prototype.D=function(a,b,c,d,e){if(c<d){var f="_"+V4++;c=c/1E3-this.K;d=d/1E3-this.K;a=new U4(c,d-c,5,f,{textAlign:0,gm:0,Yj:2.5*b,ao:5.33*a});e=new T4(c,d-c,5,f,e);this.B.push(a);this.B.push(e)}};
g.x(o5,W4);o5.prototype.B=function(a){a=new l5(a,a.byteLength,this.C);if(Oib(a)){for(;a.byteOffset<a.j.byteLength;)for(0===a.version?a.C=n5(a)*(1E3/45):1===a.version&&(a.C=4294967296*n5(a)+n5(a)),a.G=m5(a);0<a.G;a.G--){var b=m5(a),c=m5(a),d=m5(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.j,b.j.push({time:a.C,type:this.track,sU:c,tU:d,order:b.j.length}))}Aib(this.j,a);return a.B}return[]};
o5.prototype.reset=function(){this.j.clear()};g.x(p5,W4);
p5.prototype.B=function(a,b){var c=[];a=a.split(sjb);for(var d=1;d<a.length;d++){var e=a[d],f=b;if(""!==e&&!tjb.test(e)){var h=ujb.exec(e);if(h&&4<=h.length){var l=Rib(h[1]),m=Rib(h[2])-l;l+=f;var n=(h=h[3])?h.split(" "):[];h={};var p=null;var q="";var t=null,u="";n=g.v(n);for(var y=n.next();!y.done;y=n.next())if(y=y.value.split(":"),2===y.length){var A=y[1];switch(y[0]){case "line":y=A.split(",");y[0].endsWith("%")&&(p=y[0],h.ao=Number.parseInt(p,10),2===y.length&&(q=y[1].trim()));break;case "position":y=
A.split(",");t=y[0];h.Yj=Number.parseInt(t,10);2===y.length&&(u=y[1].trim());break;case "align":switch(A){case "start":h.textAlign=0;break;case "middle":h.textAlign=2;break;case "end":h.textAlign=1}}}p||q||(q="end");if(!t)switch(h.textAlign){case 0:h.Yj=0;break;case 1:h.Yj=100;break;case 2:h.Yj=50}if(null!=h.textAlign){p=0;switch(q){case "center":p+=3;break;case "end":p+=6;break;default:p+=0}switch(u){case "line-left":p+=0;break;case "center":p+=1;break;case "line-right":p+=2;break;default:switch(h.textAlign){case 0:p+=
0;break;case 2:p+=1;break;case 1:p+=2}}q=0>p||8<p?7:p;h.gm=q}e=e.substring(ujb.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");u=h;h=e;e={};if(0>h.indexOf("<")&&0>h.indexOf("&"))f=Sib(l,m,5,u),m=new T4(l,m,5,f.id,h,!1,g.hd(e)?void 0:e),c.push(f),c.push(m),f.j.push(m);else for(q=h.split(vjb),1===q.length?(h=5,u=Sib(l,m,h,u)):(p=h=6,u=Object.assign({Hs:32},u),u=new U4(l,m,p,"_"+V4++,u)),c.push(u),p=l,t=0;t<q.length;t++)n=q[t],0===t%2?(y=g.bab("<html>"+n+"</html>"),y.getElementsByTagName("parsererror").length?
(A=y.createElement("span"),A.appendChild(y.createTextNode(n))):A=y.firstChild,Qib(this,p,m-(p-l),h,u,0<t,A,e,c)):p=Rib(n)+f}ujb.lastIndex=0}}return c};
var tjb=/^NOTE/,sjb=/(?:\r\n|\r|\n){2,}/,ujb=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),vjb=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.vU.oD(p5,{B:"wvppt"});g.x(q5,g.G);q5.prototype.clear=function(){this.parser&&this.parser.dispose();this.parser=null};
q5.prototype.reset=function(){this.parser&&this.parser.reset()};
q5.prototype.ya=function(){g.G.prototype.ya.call(this);this.clear()};var z5={windowColor:"#080808",windowOpacity:0,textAlign:2,gm:7,Yj:50,ao:100,isDefault:!0,We:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.x(r5,g.CR);g.k=r5.prototype;g.k.ya=function(){if(this.D||this.Ca){var a=this.J.Af();a&&!a.isDisposed()&&a.Cy()}else pjb(this,!1);g.CR.prototype.ya.call(this)};
g.k.Pw=function(){if(this.eb)return this.D||this.Ca;var a=this.player.getAudioTrack();if(fjb(this)){if(!a.captionTracks.length)return!1;if(!this.j)return!0}a=Lhb(a,g.GN(this.Z));return"CAPTIONS_INITIAL_STATE_ON_REQUIRED"===a?!0:"CAPTIONS_INITIAL_STATE_OFF_REQUIRED"===a?s5(this):djb(this)||s5(this)?!0:ejb(this)};
g.k.load=function(){var a=this;g.CR.prototype.load.call(this);this.S=this.player.getAudioTrack();this.j?this.B&&(this.jb.clear(),this.D?jjb(this,!0):3!==this.player.getPresentingPlayerType()&&this.j.Jt(this.B,"json3",function(b,c,d,e){if(b){var f;kjb(a,null!=(f=a.B)?f:void 0);a.j.PP()&&(a.Ia=[],a.J.mf("captions"),g.ar(a.Oa),a.jb.reset());b=Yib(a.jb,b,c,d,e);a.player.yf(b,void 0,a.kb);!a.qa||a.Ca||v5(a)||g.zN(a.Z)||g.tN(a.Z)||g.pH(a.Z)||"shortspage"===a.Z.Va||a.player.isInline()||(g.er(a.Pa),b=nib({gm:0,
Yj:5,ao:5,Ar:2,textAlign:0,Gi:0,lang:"en"}),a.Va=[b],c=["Click "," for settings"],a.tb||(d=new g.oG(g.nsa()),g.H(a,d),a.tb=d.element),d=b.end-b.start,(e=g.WN(a.B))&&a.Va.push(new T4(b.start,d,0,b.id,e)),a.Va.push(new T4(b.start,d,0,b.id,c[0]),new T4(b.start,d,0,b.id,a.tb,!0),new T4(b.start,d,0,b.id,c[1],!0)),a.player.yf(a.Va),g.cr(a.Pa));!a.qa||a.Ca||v5(a)||(g.GN(a.Z)?x5(a,!0):y5(a,!0),a.S&&(a.S.D=a.B),a.player.uo());a.qa=!1}}),this.D||this.Ca||v5(this)||this.player.Ua("captionschanged",g.XN(this.B))):
(this.j=gjb(this),g.H(this,this.j),this.j.Oz(function(){ijb(a)}))};
g.k.unload=function(){this.D&&this.B?jjb(this,!1):(this.Pa&&g.er(this.Pa),this.player.mf("captions"),this.Ia=[],this.j&&this.j.Vr(),this.jb.clear(),this.ma&&this.player.yf(this.ma),this.sR());g.CR.prototype.unload.call(this);this.player.uo();this.player.Ua("captionschanged",{})};
g.k.create=function(){this.Pw()&&this.load();var a;a:{var b,c,d;if(this.Z.N("suggest_caption_correction_menu_item")&&this.Z.N("web_player_nitrate_promo_tooltip")&&(null==(b=this.videoData.getPlayerResponse())?0:null==(c=b.captions)?0:null==(d=c.playerCaptionsTracklistRenderer)?0:d.openTranscriptCommand)){var e,f;if(b=null==(a=this.videoData.getPlayerResponse())?void 0:null==(e=a.captions)?void 0:null==(f=e.playerCaptionsTracklistRenderer)?void 0:f.captionTracks)for(a=g.v(b),e=a.next();!e.done;e=a.next())if(e=
e.value,"asr"===e.kind&&"en"===e.languageCode){a=!0;break a}}a=!1}a&&this.J.va("showpromotooltip",this.K.element)};
g.k.X8=function(){for(var a=this.J.Af().Db().textTracks,b=null,c=0;c<a.length;c++)if("showing"===a[c].mode)a:{b=a[c].id;for(var d=g.DR(this.j.j,!0),e=0;e<d.length;e++)if(d[e].toString()===b){b=d[e];break a}b=null}(this.loaded?this.B:null)!==b&&w5(this,b,!0)};
g.k.X$=function(){!this.B&&this.D||this.unload()};
g.k.onCueRangeEnter=function(a){this.Ia.push(a);g.ar(this.Oa)};
g.k.onCueRangeExit=function(a){g.Eb(this.Ia,a);this.j instanceof O4&&this.j.K&&this.player.Op([a]);g.ar(this.Oa)};
g.k.getCaptionWindowContainerId=function(){return this.K.element.id};
g.k.P9=function(){ojb(this,this.Va);this.Va=null};
g.k.qR=function(){var a=this;if(!this.Wb||!this.D){this.Oa.stop();g.dba(this.Za);this.Ia.sort(g.IIa);var b=this.Ia;if(this.ma){var c=g.tp(b,function(f){return-1===this.ma.indexOf(f)},this);
c.length&&(b=c)}b=g.v(b);for(c=b.next();!c.done;c=b.next())mjb(this,c.value);b=g.v(Object.entries(this.ra));var d=b.next();for(c={};!d.done;c={Nv:c.Nv,Sm:c.Sm},d=b.next()){var e=g.v(d.value);d=e.next().value;e=e.next().value;c.Nv=d;c.Sm=e;this.Za[c.Nv]?(c.Sm.element.parentNode||(c.Sm instanceof S4||c.Sm instanceof R4||g.Yc(this.ra,function(f){return function(h,l){l!==f.Nv&&h.B.params.gm===f.Sm.B.params.gm&&h.B.params.Yj===f.Sm.B.params.Yj&&h.B.params.ao===f.Sm.B.params.ao&&(h.dispose(),delete a.ra[l]);
return l===f.Nv}}(c),this),this.K.element.appendChild(c.Sm.element)),c.Sm.XA(this.Za[c.Nv])):(c.Sm.dispose(),delete this.ra[c.Nv])}}};
g.k.U9=function(){bjb(this,{},!0);this.player.Ua("captionssettingschanged")};
g.k.N4=function(){var a=z5.We;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:z5.windowColor,windowOpacity:z5.windowOpacity};var b=Shb()||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&(a.backgroundOpacity=
b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&(a.fontSizeIncrement=
b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);null!=b.windowOpacity&&
(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.k.f_=function(a,b){var c={};Object.assign(c,Shb());Object.assign(c,a);bjb(this,c,b);this.player.Ua("captionssettingschanged")};
g.k.sR=function(){!this.D&&this.loaded&&(g.Sc(this.ra,function(a,b){a.dispose();delete this.ra[b]},this),this.qR())};
g.k.Kh=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.pe(b,-2,4);this.f_({fontSizeIncrement:c});return c;case "reload":b&&!this.D&&w5(this,this.B,!0);break;case "stickyLoading":void 0!==b&&this.Z.K&&(g.GN(this.Z)?x5(this,!!b):y5(this,!!b));break;case "track":if(!this.j)return{};if(b){if(this.D)break;if(!g.Xa(b))break;if(g.hd(b)){w5(this,null,!0);break}a=g.DR(this.j.j,!0);for(var d=0;d<a.length;d++){var e=a[d];e.languageCode!==b.languageCode||c&&(e.languageName!==b.languageName||
(e.captionId||"")!==(b.captionId||""))||(c=b.translationLanguage?Mhb(e,b.translationLanguage):e)}this.WJ(b.position);!c||c===this.B&&this.loaded||(b=g.yza(),a=g.YN(c),b.length&&a===b[b.length-1]||(b.push(a),g.OB("yt-player-caption-language-preferences",b)),g.GN(this.Z)&&!this.J.isInline()&&g.OB("yt-player-caption-sticky-language",a,2592E3),w5(this,c,!0))}else return this.loaded&&this.B&&!v5(this)?g.XN(this.B):{};return"";case "tracklist":return this.j?g.zn(g.DR(this.j.j,!(!b||!b.includeAsr)),function(f){return g.XN(f)}):
[];
case "translationLanguages":return this.j?this.j.D.map(function(f){return Object.assign({},f)}):[];
case "sampleSubtitles":this.D||void 0===b||pjb(this,!!b);break;case "sampleSubtitlesCustomized":this.D||pjb(this,!!b,b);break;case "recommendedTranslationLanguages":return g.yza();case "defaultTranslationSourceTrackIndices":return this.j?this.j.S:[]}};
g.k.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.Z.K&&a.push("stickyLoading");return a};
g.k.Dq=function(){var a=this.B;if(this.Z.N("html5_modify_caption_vss_logging")){var b;return(a=null!=(b=this.videoData.CB)?b:null)?{cc:g.$Ea(a)}:{}}return a?(b=a.vssId,a.translationLanguage&&b&&(b="t"+b+"."+g.YN(a)),{cc:b}):{}};
g.k.L$=function(){this.isSubtitlesOn()?(g.GN(this.Z)?x5(this,!1):y5(this,!1),kjb(this),this.unload(),s5(this,!0)&&w5(this,t5(this),!1)):this.MZ()};
g.k.MZ=function(){this.isSubtitlesOn()||w5(this,v5(this)||!this.B?u5(this,!0):this.B,!0)};
g.k.isSubtitlesOn=function(){return!!this.loaded&&!!this.B&&!v5(this)};
g.k.Q6=function(){var a=v5(this);s5(this,a)?w5(this,this.player.getAudioTrack().j,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),fjb(this)&&(this.qa=!1,this.B=null,this.j&&(this.j.dispose(),this.j=null)),this.Pw()&&(a?w5(this,u5(this),!1):this.load()))};
g.k.WJ=function(a){a&&(this.ea={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.K.element.style.top=100*this.ea.top+"%",this.K.element.style.left=100*this.ea.left+"%",this.K.element.style.width=100*this.ea.width+"%",this.K.element.style.height=100*this.ea.height+"%",this.K.element.style.position="absolute",a=njb(this))&&(this.K.element.style.width=a.width+"px",this.K.element.style.height=a.height+"px")};
g.k.y7=function(){var a=this.J.Af();a&&!a.isDisposed()&&a.Cy();this.J.isFullscreen()?(this.D=this.eb=!0,this.loaded&&ijb(this)):(this.eb="3"===this.Z.controlsType,this.D=ajb(this));w5(this,this.B)};
g.k.qK=function(){var a,b,c,d=null==(a=this.videoData.getPlayerResponse())?void 0:null==(b=a.captions)?void 0:null==(c=b.playerCaptionsTracklistRenderer)?void 0:c.openTranscriptCommand;d&&this.player.Ua("innertubeCommand",d)};
g.vU.oD(r5,{qR:"smucd"});g.BR("captions",r5);})(_yt_player);
