(function(g){var window=this;'use strict';var ulb=function(a,b){a.Ua("onAutonavCoundownStarted",b)},l6=function(a,b,c){g.Br(a.element,"ytp-suggestion-set",!!b.videoId);
var d=b.playlistId;c=b.Kg(c?c:"mqdefault.jpg");var e=null,f=null;b instanceof g.BO&&(b.lengthText?(e=b.lengthText||null,f=b.cw||null):b.lengthSeconds&&(e=g.iH(b.lengthSeconds),f=g.iH(b.lengthSeconds,!0)));var h=!!d;d=h&&"RD"===g.zFa(d).type;var l=b instanceof g.BO?b.isLivePlayback:null,m=b instanceof g.BO?b.isUpcoming:null,n=b.author,p=b.shortViewCount,q=b.publishedTimeText,t=[],u=[];n&&t.push(n);p&&(t.push(p),u.push(p));q&&u.push(q);c={title:b.title,author:n,author_and_views:t.join(" \u2022 "),aria_label:b.ariaLabel||
g.IQ("Watch $TITLE",{TITLE:b.title}),duration:e,timestamp:f,url:b.Pk(),is_live:l,is_upcoming:m,is_list:h,is_mix:d,background:c?"background-image: url("+c+")":"",views_and_publish_time:u.join(" \u2022 "),autoplayAlternativeHeader:b.Cs};b instanceof g.AO&&(c.playlist_length=b.playlistLength);a.update(c)},m6=function(a){var b=a.W(),c=b.D;
g.W.call(this,{I:"a",T:"ytp-autonav-suggestion-card",Y:{href:"{{url}}",target:c?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",Na:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],Aa:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Aa:"Live"},{I:"div",
Na:["ytp-autonav-upcoming-stamp"],Aa:"Upcoming"},{I:"div",T:"ytp-autonav-list-overlay",X:[{I:"div",T:"ytp-autonav-mix-text",Aa:"Mix"},{I:"div",T:"ytp-autonav-mix-icon"}]}]},{I:"div",Na:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Aa:"{{title}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Aa:"{{author}}"},{I:"div",Na:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Aa:"{{views_and_publish_time}}"}]});this.J=a;this.suggestion=
null;this.j=c;this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress)},n6=function(a,b){b=void 0===b?!1:b;
g.W.call(this,{I:"div",T:"ytp-autonav-endscreen-countdown-overlay"});var c=this;this.K=b;this.G=void 0;this.C=0;this.container=new g.W({I:"div",T:"ytp-autonav-endscreen-countdown-container"});g.H(this,this.container);this.container.Ga(this.element);b=a.W();var d=b.D;this.J=a;this.suggestion=null;this.onVideoDataChange("newdata",this.J.getVideoData());this.V(a,"videodatachange",this.onVideoDataChange);this.j=new g.W({I:"div",T:"ytp-autonav-endscreen-upnext-container",Y:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},X:[{I:"div",T:"ytp-autonav-endscreen-upnext-header"},{I:"div",T:"ytp-autonav-endscreen-upnext-alternative-header",Aa:"{{autoplayAlternativeHeader}}"},{I:"a",T:"ytp-autonav-endscreen-link-container",Y:{href:"{{url}}",target:d?b.ea:""},X:[{I:"div",T:"ytp-autonav-endscreen-upnext-thumbnail",Y:{style:"{{background}}"},X:[{I:"div",Y:{"aria-label":"{{timestamp}}"},Na:["ytp-autonav-timestamp"],
Aa:"{{duration}}"},{I:"div",Na:["ytp-autonav-live-stamp"],Aa:"Live"},{I:"div",Na:["ytp-autonav-upcoming-stamp"],Aa:"Upcoming"}]},{I:"div",T:"ytp-autonav-endscreen-video-info",X:[{I:"div",T:"ytp-autonav-endscreen-premium-badge"},{I:"div",T:"ytp-autonav-endscreen-upnext-title",Aa:"{{title}}"},{I:"div",T:"ytp-autonav-endscreen-upnext-author",Aa:"{{author}}"},{I:"div",T:"ytp-autonav-view-and-date",Aa:"{{views_and_publish_time}}"},{I:"div",T:"ytp-autonav-author-and-view",Aa:"{{author_and_views}}"}]}]}]});
g.H(this,this.j);this.j.Ga(this.container.element);d||this.V(this.j.Ha("ytp-autonav-endscreen-link-container"),"click",this.UR);this.J.yb(this.container.element,this,115127);this.J.yb(this.j.Ha("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.W({I:"div",T:"ytp-autonav-overlay"});g.H(this,this.overlay);this.overlay.Ga(this.container.element);this.B=new g.W({I:"div",T:"ytp-autonav-endscreen-button-container"});g.H(this,this.B);this.B.Ga(this.container.element);this.cancelButton=
new g.W({I:"button",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{"aria-label":"Cancel autoplay"},Aa:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ga(this.B.element);this.cancelButton.Ta("click",this.t0,this);this.J.yb(this.cancelButton.element,this,115129);this.playButton=new g.W({I:"a",Na:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
b.N("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],Y:{href:"{{url}}",role:"button","aria-label":"Play next video"},Aa:"Play Now"});g.H(this,this.playButton);this.playButton.Ga(this.B.element);this.playButton.Ta("click",this.UR,this);this.J.yb(this.playButton.element,this,115130);this.D=new g.br(function(){vlb(c)},500);
g.H(this,this.D);this.TR();this.V(a,"autonavvisibility",this.TR);this.J.N("web_autonav_color_transition")&&(this.V(a,"autonavchange",this.s0),this.V(a,"onAutonavCoundownStarted",this.R6))},o6=function(a){var b=a.J.Ok(!0,a.J.isFullscreen());
g.Br(a.container.element,"ytp-autonav-endscreen-small-mode",a.Ng(b));g.Br(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.KJ);g.Br(a.J.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.J.Cf());g.Br(a.J.getRootNode(),"countdown-running",a.Sk());g.Br(a.container.element,"ytp-player-content",a.J.Cf());g.zo(a.overlay.element,{width:b.width+"px"});if(!a.Sk()){a.J.Cf()?wlb(a,Math.round(xlb(a)/1E3)):wlb(a);b=!!a.suggestion&&!!a.suggestion.Cs;var c=a.J.Cf()||!b;
g.Br(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!c&&b);g.Br(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",c&&!b);g.rG(a.B,a.J.Cf());g.Br(a.element,"ytp-enable-w2w-color-transitions",ylb(a))}},vlb=function(a){var b=xlb(a),c=Math,d=c.min;
var e=a.C?Date.now()-a.C:0;c=d.call(c,e,b);wlb(a,Math.ceil((b-c)/1E3));500>=b-c&&a.Sk()?a.select(!0):a.Sk()&&a.D.start()},xlb=function(a){if(a.J.isFullscreen()){var b;
a=null==(b=a.J.getVideoData())?void 0:b.zB;return-1===a||void 0===a?8E3:a}return 0<=a.J.Ss()?a.J.Ss():g.YI(a.J.W().experiments,"autoplay_time")||1E4},ylb=function(a){var b;
return!(null==(b=a.J.getVideoData())||!b.watchToWatchTransitionRenderer)},wlb=function(a,b){b=void 0===b?-1:b;
a=a.j.Ha("ytp-autonav-endscreen-upnext-header");g.cf(a);if(0<=b){b=String(b);var c="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],d="Up next in $SECONDS".indexOf(c);if(0<=d){a.appendChild(g.af("Up next in $SECONDS".slice(0,d)));var e=g.$e("span");g.hr(e,"ytp-autonav-endscreen-upnext-header-countdown-number");g.of(e,b);a.appendChild(e);a.appendChild(g.af("Up next in $SECONDS".slice(d+c.length)));return}}g.of(a,"Up next")},p6=function(a,b){g.W.call(this,{I:"div",
Na:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},q6=function(a){g.W.call(this,{I:"div",
Na:["ytp-upnext","ytp-player-content"],Y:{"aria-label":"{{aria_label}}"},X:[{I:"div",T:"ytp-cued-thumbnail-overlay-image",Y:{style:"{{background}}"}},{I:"span",T:"ytp-upnext-top",X:[{I:"span",T:"ytp-upnext-header",Aa:"Up Next"},{I:"span",T:"ytp-upnext-title",Aa:"{{title}}"},{I:"span",T:"ytp-upnext-author",Aa:"{{author}}"}]},{I:"a",T:"ytp-upnext-autoplay-icon",Y:{role:"button",href:"{{url}}","aria-label":"Play next video"},X:[{I:"svg",Y:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
X:[{I:"circle",T:"ytp-svg-autoplay-circle",Y:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{I:"circle",T:"ytp-svg-autoplay-ring",Y:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{I:"path",T:"ytp-svg-fill",Y:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{I:"span",T:"ytp-upnext-bottom",X:[{I:"span",T:"ytp-upnext-cancel"},{I:"span",T:"ytp-upnext-paused",
Aa:"Autoplay is paused"}]}]});this.api=a;this.cancelButton=null;this.G=this.Ha("ytp-svg-autoplay-ring");this.C=this.notification=this.j=this.suggestion=null;this.D=new g.br(this.sG,5E3,this);this.B=0;var b=this.Ha("ytp-upnext-cancel");this.cancelButton=new g.W({I:"button",Na:["ytp-upnext-cancel-button","ytp-button"],Y:{tabindex:"0","aria-label":"Cancel autoplay"},Aa:"Cancel"});g.H(this,this.cancelButton);this.cancelButton.Ta("click",this.u0,this);this.cancelButton.Ga(b);this.cancelButton&&this.api.yb(this.cancelButton.element,
this,115129);g.H(this,this.D);this.api.yb(this.element,this,18788);b=this.Ha("ytp-upnext-autoplay-icon");this.V(b,"click",this.v0);this.api.yb(b,this,115130);this.VR();this.V(a,"autonavvisibility",this.VR);this.V(a,"mdxnowautoplaying",this.A7);this.V(a,"mdxautoplaycanceled",this.B7);g.Br(this.element,"ytp-upnext-mobile",this.api.W().B)},zlb=function(a,b){if(b)return b;
if(a.api.isFullscreen()){var c;a=null==(c=a.api.getVideoData())?void 0:c.zB;return-1===a||void 0===a?8E3:a}return 0<=a.api.Ss()?a.api.Ss():g.YI(a.api.W().experiments,"autoplay_time")||1E4},Alb=function(a,b){b=zlb(a,b);
var c=Math,d=c.min;var e=(0,g.JC)()-a.B;c=d.call(c,e,b);b=0===b?1:Math.min(c/b,1);a.G.setAttribute("stroke-dashoffset",""+-211*(b+1));1<=b&&a.Sk()&&3!==a.api.getPresentingPlayerType()?a.select(!0):a.Sk()&&a.j.start()},r6=function(a){p6.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.W({I:"div",T:"ytp-suggestion-panel",X:[{I:"div",Na:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Aa:"More videos"}]});this.S=new g.W({I:"div",T:"ytp-suggestions-container"});this.videos=[];this.C=null;this.G=this.K=!1;this.B=new n6(this.player);g.H(this,this.B);this.B.Ga(this.element);a.getVideoData().Ue?this.j=this.B:(this.j=new q6(a),g.jQ(this.player,this.j.element,4),g.H(this,this.j));this.overlay=new g.W({I:"div",
T:"ytp-autonav-overlay-cancelled-state"});g.H(this,this.overlay);this.overlay.Ga(this.element);this.D=new g.KL(this);g.H(this,this.D);g.H(this,this.table);this.table.Ga(this.element);this.table.show();g.H(this,this.S);this.S.Ga(this.table.element);this.hide()},s6=function(a){var b=a.Cf();
b!==a.G&&(a.G=b,a.player.va("autonavvisibility"),a.G?(a.B!==a.j&&a.B.hide(),a.table.hide()):(a.B!==a.j&&a.B.show(),a.table.show()))},t6=function(a,b){g.W.call(this,{I:"button",
Na:["ytp-watch-on-youtube-button","ytp-button"],Aa:"{{content}}"});this.J=a;this.buttonType=this.buttonType=b;this.updateButton();2===this.buttonType&&g.jr(this.element,"ytp-continue-watching-button");this.Ta("click",this.onClick);this.Ta("videodatachange",this.updateButton);g.rG(this,!0)},u6=function(a,b){p6.call(this,a,"embeds-lite-endscreen");
this.J=a;this.wb=b;this.J.yb(this.element,this,156943);this.watchButton=new t6(a,2);g.H(this,this.watchButton);this.watchButton.Ga(this.element);this.hide()},Blb=function(a){p6.call(this,a,"subscribecard-endscreen");
this.j=new g.W({I:"div",T:"ytp-subscribe-card",X:[{I:"img",T:"ytp-author-image",Y:{src:"{{profilePicture}}"}},{I:"div",T:"ytp-subscribe-card-right",X:[{I:"div",T:"ytp-author-name",Aa:"{{author}}"},{I:"div",T:"html5-subscribe-button-container"}]}]});g.H(this,this.j);this.j.Ga(this.element);var b=a.getVideoData();this.subscribeButton=new g.pS("Subscribe",null,"Unsubscribe",null,!0,!1,b.Hl,b.subscribed,"trailer-endscreen",null,a);g.H(this,this.subscribeButton);this.subscribeButton.Ga(this.j.Ha("html5-subscribe-button-container"));
this.V(a,"videodatachange",this.Sa);this.Sa();this.hide()},v6=function(a){var b=a.W(),c=g.NL||g.mN?{style:"will-change: opacity"}:void 0,d=b.D,e=["ytp-videowall-still"];
b.B&&e.push("ytp-videowall-show-text");g.W.call(this,{I:"a",Na:e,Y:{href:"{{url}}",target:d?b.ea:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},X:[{I:"div",T:"ytp-videowall-still-image",Y:{style:"{{background}}"}},{I:"span",T:"ytp-videowall-still-info",Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-info-bg",X:[{I:"span",T:"ytp-videowall-still-info-content",Y:c,X:[{I:"span",T:"ytp-videowall-still-info-title",Aa:"{{title}}"},
{I:"span",T:"ytp-videowall-still-info-author",Aa:"{{author_and_views}}"},{I:"span",T:"ytp-videowall-still-info-live",Aa:"Live"},{I:"span",T:"ytp-videowall-still-info-duration",Aa:"{{duration}}"}]}]}]},{I:"span",Na:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-listlabel-icon"},"Playlist",{I:"span",T:"ytp-videowall-still-listlabel-length",X:[" (",{I:"span",Aa:"{{playlist_length}}"},")"]}]},{I:"span",Na:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],Y:{"aria-hidden":"true"},X:[{I:"span",T:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{I:"span",T:"ytp-videowall-still-listlabel-length",Aa:" (50+)"}]}]});this.suggestion=null;this.B=d;this.api=a;this.j=new g.KL(this);g.H(this,this.j);this.Ta("click",this.onClick);this.Ta("keypress",this.onKeyPress);this.j.V(a,"videodatachange",this.onVideoDataChange);a.Zf(this.element,this);this.onVideoDataChange()},w6=function(a){p6.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.C=0;this.stills=[];this.D=this.videoData=null;this.G=this.S=!1;this.ea=null;this.B=new g.KL(this);g.H(this,this.B);this.K=new g.br(function(){g.jr(b.element,"ytp-show-tiles")},0);
g.H(this,this.K);var c=new g.W({I:"button",Na:["ytp-button","ytp-endscreen-previous"],Y:{"aria-label":"Previous"},X:[g.xG()]});g.H(this,c);c.Ga(this.element);c.Ta("click",this.z0,this);this.table=new g.oG({I:"div",T:"ytp-endscreen-content"});g.H(this,this.table);this.table.Ga(this.element);c=new g.W({I:"button",Na:["ytp-button","ytp-endscreen-next"],Y:{"aria-label":"Next"},X:[g.yG()]});g.H(this,c);c.Ga(this.element);c.Ta("click",this.y0,this);a.getVideoData().Ue?this.j=new n6(a,!0):this.j=new q6(a);
g.H(this,this.j);g.jQ(this.player,this.j.element,4);a.yb(this.element,this,158789);this.hide()},x6=function(a){return g.kQ(a.player)&&a.eC()&&!a.D},y6=function(a){var b=a.Cf();
b!==a.S&&(a.S=b,a.player.va("autonavvisibility"))},z6=function(a){p6.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new t6(a,1);g.H(this,this.watchButton);this.watchButton.Ga(this.element);g.cab(a)&&(this.j=new g.E2(a,g.SP(a)),g.H(this,this.j),this.B=new g.W({I:"div",Na:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],Y:{tabIndex:"-1"},X:[this.j]}),g.H(this,this.B),this.j.Ga(this.B.element),this.B.Ga(this.element));a.yb(this.element,this,156914);this.hide()},Flb=function(a){g.CR.call(this,a);
var b=this;this.endScreen=null;this.B=this.j=this.C=this.D=!1;this.listeners=new g.KL(this);g.H(this,this.listeners);var c=a.W(),d=a.getVideoData();d=d&&0!==d.limitedPlaybackDurationInSeconds;g.pB(g.wN(c))&&d&&!g.fQ(a)?(this.B=!0,this.endScreen=new u6(a,g.SP(a))):g.gQ(a)?this.endScreen=new z6(a):Clb(a)?(this.D=!0,Dlb(this),this.j?this.endScreen=new r6(a):this.endScreen=new w6(a)):c.eh?this.endScreen=new Blb(a):this.endScreen=new p6(a);g.H(this,this.endScreen);g.jQ(a,this.endScreen.element,4);Elb(this);
this.listeners.V(a,"videodatachange",this.onVideoDataChange,this);this.listeners.V(a,g.JP("endscreen"),function(e){b.onCueRangeEnter(e)});
this.listeners.V(a,g.KP("endscreen"),function(e){b.onCueRangeExit(e)})},Dlb=function(a){var b=a.player.getVideoData();
if(!b||a.j===b.Ol&&a.C===b.Ue)return!1;a.j=b.Ol;a.C=b.Ue;return!0},Clb=function(a){a=a.W();
return a.Td&&!a.eh},Elb=function(a){a.player.mf("endscreen");
var b=a.player.getVideoData();b=new g.IP(Math.max(1E3*(b.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var c=new g.IP(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.yf([b,c])};
g.fU.prototype.TA=g.ba(37,function(a){this.DP!==a&&(this.DP=a,this.Gl())});
g.VS.prototype.Gr=g.ba(36,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.fU.prototype.Gr=g.ba(35,function(a){this.shareButton&&this.shareButton.Gr(a)});
g.QS.prototype.Fr=g.ba(34,function(a){this.j!==a&&(this.j=a,this.Sa())});
g.fU.prototype.Fr=g.ba(33,function(a){this.overflowButton&&this.overflowButton.Fr(a)});
g.gS.prototype.XE=g.ba(32,function(a){this.EP!==a&&(this.EP=a,this.Vp())});
g.bQ.prototype.Ss=g.ba(6,function(){return this.app.Ss()});
g.kY.prototype.Ss=g.ba(5,function(){return this.getVideoData().FT});g.x(m6,g.W);m6.prototype.select=function(){this.J.Ao(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yC||void 0)&&this.J.ub(this.element)};
m6.prototype.onClick=function(a){g.JQ(a,this.J,this.j,this.suggestion.sessionData||void 0)&&this.select()};
m6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.rQ(a)||(this.select(),g.sQ(a))}};g.x(n6,g.W);g.k=n6.prototype;g.k.BF=function(a){this.suggestion!==a&&(this.suggestion=a,l6(this.j,a),this.playButton.updateValue("url",this.suggestion.Pk()),o6(this))};
g.k.Sk=function(){return 0<this.C};
g.k.aB=function(){this.Sk()||(this.C=Date.now(),vlb(this),ulb(this.J,xlb(this)),g.Br(this.J.getRootNode(),"countdown-running",this.Sk()))};
g.k.Bw=function(){this.Or();vlb(this);var a=this.j.Ha("ytp-autonav-endscreen-upnext-header");a&&g.of(a,"Up next")};
g.k.Or=function(){this.Sk()&&(this.D.stop(),this.C=0)};
g.k.select=function(a){this.J.nextVideo(!1,void 0===a?!1:a);this.Or()};
g.k.UR=function(a){g.JQ(a,this.J)&&(a.currentTarget===this.playButton.element?this.J.ub(this.playButton.element):a.currentTarget===this.j.Ha("ytp-autonav-endscreen-link-container")&&(a=this.j.Ha("ytp-autonav-endscreen-link-container"),this.J.Ya(a,!0),this.J.ub(a)),this.select())};
g.k.t0=function(){this.J.ub(this.cancelButton.element);g.dQ(this.J,!0);this.G&&this.J.Ua("innertubeCommand",this.G)};
g.k.onVideoDataChange=function(a,b){var c;this.G=null==(c=b.x4)?void 0:c.command};
g.k.R6=function(a){if(ylb(this)){var b=this.J.getVideoData().watchToWatchTransitionRenderer,c=null==b?void 0:b.fromColorPaletteDark;b=null==b?void 0:b.toColorPaletteDark;if(c&&b){var d=this.element;d.style.setProperty("--w2w-start-background-color",g.qH(c.surgeColor));d.style.setProperty("--w2w-start-primary-text-color",g.qH(c.primaryTitleColor));d.style.setProperty("--w2w-start-secondary-text-color",g.qH(c.secondaryTitleColor));d.style.setProperty("--w2w-end-background-color",g.qH(b.surgeColor));
d.style.setProperty("--w2w-end-primary-text-color",g.qH(b.primaryTitleColor));d.style.setProperty("--w2w-end-secondary-text-color",g.qH(b.secondaryTitleColor));d.style.setProperty("--w2w-animation-duration",a+"ms")}g.Br(this.element,"ytp-w2w-animate",!0)}};
g.k.s0=function(a){this.J.N("web_autonav_color_transition")&&2!==a&&g.Br(this.element,"ytp-w2w-animate",!1)};
g.k.TR=function(){var a=this.J.Cf();this.K&&this.Hb!==a&&g.rG(this,a);o6(this);this.J.Ya(this.container.element,a);this.J.Ya(this.cancelButton.element,a);this.J.Ya(this.j.Ha("ytp-autonav-endscreen-link-container"),a);this.J.Ya(this.playButton.element,a)};
g.k.Ng=function(a){return 400>a.width||459>a.height};g.x(p6,g.W);g.k=p6.prototype;g.k.create=function(){this.created=!0};
g.k.destroy=function(){this.created=!1};
g.k.eC=function(){return!1};
g.k.Cf=function(){return!1};
g.k.HW=function(){return!1};g.x(q6,g.W);g.k=q6.prototype;g.k.sG=function(){this.notification&&(this.D.stop(),this.Pc(this.C),this.C=null,this.notification.close(),this.notification=null)};
g.k.BF=function(a){this.suggestion=a;l6(this,a,"hqdefault.jpg")};
g.k.VR=function(){g.rG(this,this.api.Cf());this.api.Ya(this.element,this.api.Cf());this.api.Ya(this.Ha("ytp-upnext-autoplay-icon"),this.api.Cf());this.cancelButton&&this.api.Ya(this.cancelButton.element,this.api.Cf())};
g.k.J7=function(){window.focus();this.sG()};
g.k.aB=function(a){var b=this;this.Sk()||(g.oE("a11y-announce","Up Next "+this.suggestion.title),this.B=(0,g.JC)(),this.j=new g.br(function(){Alb(b,a)},25),Alb(this,a),ulb(this.api,zlb(this,a)));
g.lr(this.element,"ytp-upnext-autoplay-paused")};
g.k.hide=function(){g.W.prototype.hide.call(this)};
g.k.Sk=function(){return!!this.j};
g.k.Bw=function(){this.Or();this.B=(0,g.JC)();Alb(this);g.jr(this.element,"ytp-upnext-autoplay-paused")};
g.k.Or=function(){this.Sk()&&(this.j.dispose(),this.j=null)};
g.k.select=function(a){a=void 0===a?!1:a;if(this.api.W().N("autonav_notifications")&&a&&window.Notification&&"function"===typeof document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(this.sG(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.Kg()}),this.C=this.V(this.notification,"click",this.J7),this.D.start())}this.Or();this.api.nextVideo(!1,a)};
g.k.v0=function(a){!g.nf(this.cancelButton.element,g.qQ(a))&&g.JQ(a,this.api)&&(this.api.Cf()&&this.api.ub(this.Ha("ytp-upnext-autoplay-icon")),this.select())};
g.k.u0=function(){this.api.Cf()&&this.cancelButton&&this.api.ub(this.cancelButton.element);g.dQ(this.api,!0)};
g.k.A7=function(a){this.api.getPresentingPlayerType();this.show();this.aB(a)};
g.k.B7=function(){this.api.getPresentingPlayerType();this.Or();this.hide()};
g.k.ya=function(){this.Or();this.sG();g.W.prototype.ya.call(this)};g.x(r6,p6);g.k=r6.prototype;g.k.create=function(){p6.prototype.create.call(this);this.D.V(this.player,"appresize",this.DB);this.D.V(this.player,"onVideoAreaChange",this.DB);this.D.V(this.player,"videodatachange",this.onVideoDataChange);this.D.V(this.player,"autonavchange",this.WR);this.D.V(this.player,"autonavcancel",this.w0);this.onVideoDataChange()};
g.k.show=function(){p6.prototype.show.call(this);(this.K||this.C&&this.C!==this.videoData.clientPlaybackNonce)&&g.dQ(this.player,!1);g.kQ(this.player)&&this.eC()&&!this.C?(s6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.aB():3===this.videoData.autonavState&&this.j.Bw()):(g.dQ(this.player,!0),s6(this));this.DB()};
g.k.hide=function(){p6.prototype.hide.call(this);this.j.Bw();s6(this)};
g.k.DB=function(){var a=this.player.Ok(!0,this.player.isFullscreen());s6(this);o6(this.B);g.Br(this.element,"ytp-autonav-cancelled-small-mode",this.Ng(a));g.Br(this.element,"ytp-autonav-cancelled-tiny-mode",this.OH(a));g.Br(this.element,"ytp-autonav-cancelled-mini-mode",400>=a.width||360>=a.height);this.overlay&&g.zo(this.overlay.element,{width:a.width+"px"});if(!this.G)for(a=0;a<this.videos.length;a++)g.Br(this.videos[a].element,"ytp-suggestion-card-with-margin",1===a%2)};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;if((a=this.videoData.suggestions)&&a.length||this.player.N("web_player_autonav_empty_suggestions_fix")){var b=g.dP(this.videoData);b&&(this.j.BF(b),this.j!==this.B&&this.B.BF(b))}if(a&&a.length)for(b=0;b<Glb.length;++b){var c=Glb[b];if(a&&a[c]){this.videos[b]=new m6(this.player);var d=this.videos[b];c=a[c];d.suggestion!==c&&(d.suggestion=c,l6(d,c));g.H(this,this.videos[b]);this.videos[b].Ga(this.S.element)}}this.DB()}};
g.k.WR=function(a){1===a?(this.K=!1,this.C=this.videoData.clientPlaybackNonce,this.j.Or(),this.Hb&&this.DB()):(this.K=!0,this.Cf()&&(2===a?this.j.aB():3===a&&this.j.Bw()))};
g.k.w0=function(a){a?this.WR(1):(this.C=null,this.K=!1)};
g.k.eC=function(){return 1!==this.videoData.autonavState};
g.k.Ng=function(a){return(910>a.width||459>a.height)&&!this.OH(a)&&!(400>=a.width||360>=a.height)};
g.k.OH=function(a){return 800>a.width&&!(400>=a.width||360>=a.height)};
g.k.Cf=function(){return this.Hb&&g.kQ(this.player)&&this.eC()&&!this.C};
var Glb=[1,3,2,4];g.x(t6,g.W);g.k=t6.prototype;
g.k.updateButton=function(){var a=this.J.getVideoData();if(this.J.N("embeds_enable_server_driven_watch_again_on_youtube")){var b,c;if(b=(a=null==(b=a.zd)?void 0:null==(c=b.playerOverlays)?void 0:c.playerOverlayRenderer)&&g.Q(a.watchOnYoutubeButton,g.kKa))this.j=b}if(this.j)this.update({content:this.j.title}),this.J.mj(this.element)&&this.J.Py(this.element),this.J.Zf(this.element,this),this.J.fg(this.element,this.j.trackingParams||null);else{switch(this.buttonType){case 1:b="Watch again on YouTube";
c=156915;break;case 2:b="Continue watching on YouTube";c=156942;break;default:b="Continue watching on YouTube",c=156942}this.update({content:b});this.J.mj(this.element)&&this.J.Py(this.element);this.J.yb(this.element,this,c)}};
g.k.onClick=function(a){this.J.N("web_player_log_click_before_generating_ve_conversion_params")&&this.J.ub(this.element);this.j?this.J.Ua("innertubeCommand",g.Q(this.j.onTap,g.gG)):g.KQ(this.getVideoUrl(),this.J,a);this.J.N("web_player_log_click_before_generating_ve_conversion_params")||this.J.ub(this.element)};
g.k.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.J.getVideoUrl(a,!1,!1,!0);var b=this.J.W();if(g.nN(b)||g.vN(b)){var c={};g.nN(b)&&g.QP(this.J,"addEmbedsConversionTrackingParams",[c]);a:{switch(this.buttonType){case 2:b="emb_ytp_continue_watching";break a}b="emb_ytp_watch_again"}g.XI(c,b);a=g.gk(a,c)}return a};
g.k.Ya=function(){this.J.Ya(this.element,this.Hb&&this.ma)};
g.k.show=function(){g.W.prototype.show.call(this);this.Ya()};
g.k.hide=function(){g.W.prototype.hide.call(this);this.Ya()};
g.k.lc=function(a){g.W.prototype.lc.call(this,a);this.Ya()};g.x(u6,p6);u6.prototype.show=function(){3!==this.player.getPlayerState()&&(p6.prototype.show.call(this),this.wb.TA(!0),this.wb.Gr(!0),this.J.W().Ec||this.wb.Fr(!0),this.J.Ya(this.element,!0),this.watchButton.lc(!0))};
u6.prototype.hide=function(){p6.prototype.hide.call(this);this.wb.TA(!1);this.wb.Gr(!1);this.wb.Fr(!1);this.J.Ya(this.element,!1);this.watchButton.lc(!1)};g.x(Blb,p6);Blb.prototype.Sa=function(){var a=this.player.getVideoData();this.j.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.Hl;var b=this.subscribeButton;a.subscribed?b.j():b.B()};g.x(v6,g.W);v6.prototype.select=function(){this.api.Ao(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.yC||void 0)&&this.api.ub(this.element)};
v6.prototype.onClick=function(a){if(g.nN(this.api.W())&&this.api.N("web_player_log_click_before_generating_ve_conversion_params")){this.api.ub(this.element);var b=this.suggestion.Pk(),c={};g.gJa(this.api,c,"emb_rel_end");b=g.gk(b,c);g.KQ(b,this.api,a)}else g.JQ(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
v6.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:g.rQ(a)||(this.select(),g.sQ(a))}};
v6.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),b=this.api.W();this.B=a.Qd?!1:b.D};g.x(w6,p6);g.k=w6.prototype;g.k.create=function(){p6.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.Yp();this.B.V(this.player,"appresize",this.Yp);this.B.V(this.player,"onVideoAreaChange",this.Yp);this.B.V(this.player,"videodatachange",this.onVideoDataChange);this.B.V(this.player,"autonavchange",this.sK);this.B.V(this.player,"autonavcancel",this.x0);a=this.videoData.autonavState;a!==this.ea&&this.sK(a);this.B.V(this.element,"transitionend",this.Y8)};
g.k.destroy=function(){g.KB(this.B);g.pb(this.stills);this.stills=[];p6.prototype.destroy.call(this);g.lr(this.element,"ytp-show-tiles");this.K.stop();this.ea=this.videoData.autonavState};
g.k.eC=function(){return 1!==this.videoData.autonavState};
g.k.show=function(){var a=this.Hb;p6.prototype.show.call(this);g.lr(this.element,"ytp-show-tiles");this.player.W().B?g.dr(this.K):this.K.start();(this.G||this.D&&this.D!==this.videoData.clientPlaybackNonce)&&g.dQ(this.player,!1);x6(this)?(y6(this),2===this.videoData.autonavState?3===this.player.getVisibilityState()?this.j.select(!0):this.j.aB():3===this.videoData.autonavState&&this.j.Bw()):(g.dQ(this.player,!0),y6(this));a!==this.Hb&&this.player.Ya(this.element,!0)};
g.k.hide=function(){var a=this.Hb;p6.prototype.hide.call(this);this.j.Bw();y6(this);a!==this.Hb&&this.player.Ya(this.element,!1)};
g.k.Y8=function(a){g.qQ(a)===this.element&&this.Yp()};
g.k.Yp=function(){var a,b,c,d;var e=(null==(a=this.videoData)?0:null==(b=a.suggestions)?0:b.length)?null==(c=this.videoData)?void 0:c.suggestions:[null==(d=this.videoData)?void 0:g.dP(d)];if(e.length){g.jr(this.element,"ytp-endscreen-paginate");var f=this.J.Ok(!0,this.J.isFullscreen());if(a=g.SP(this.J))a=a.Mg()?48:32,f.width-=2*a;var h=f.width/f.height;d=96/54;b=a=2;var l=Math.max(f.width/96,2),m=Math.max(f.height/54,2);c=e.length;var n=Math.pow(2,2);var p=c*n+(Math.pow(2,2)-n);p+=Math.pow(2,2)-
n;for(p-=n;0<p&&(a<l||b<m);){var q=a/2,t=b/2,u=a<=l-2&&p>=t*n,y=b<=m-2&&p>=q*n;if((q+1)/t*d/h>h/(q/(t+1)*d)&&y)p-=q*n,b+=2;else if(u)p-=t*n,a+=2;else if(y)p-=q*n,b+=2;else break}d=!1;p>=3*n&&6>=c*n-p&&(4<=b||4<=a)&&(d=!0);n=96*a;p=54*b;h=n/p<h?f.height/p:f.width/n;h=Math.min(h,2);n=Math.floor(Math.min(f.width,n*h));p=Math.floor(Math.min(f.height,p*h));f=this.table.element;f.ariaLive="polite";g.Jo(f,n,p);g.zo(f,{marginLeft:n/-2+"px",marginTop:p/-2+"px"});this.j.BF(g.dP(this.videoData));this.j instanceof
n6&&o6(this.j);g.Br(this.element,"ytp-endscreen-takeover",x6(this));y6(this);n+=4;p+=4;h=0;f.ariaBusy="true";for(l=0;l<a;l++)for(m=0;m<b;m++)if(q=h,u=0,d&&l>=a-2&&m>=b-2?u=1:0===m%2&&0===l%2&&(2>m&&2>l?0===m&&0===l&&(u=2):u=2),q=g.qe(q+this.C,c),0!==u){t=this.stills[h];t||(t=new v6(this.player),this.stills[h]=t,f.appendChild(t.element));y=Math.floor(p*m/b);var A=Math.floor(n*l/a),E=Math.floor(p*(m+u)/b)-y-4,L=Math.floor(n*(l+u)/a)-A-4;g.Fo(t.element,A,y);g.Jo(t.element,L,E);g.zo(t.element,"transitionDelay",
(m+l)/20+"s");g.Br(t.element,"ytp-videowall-still-mini",1===u);g.Br(t.element,"ytp-videowall-still-large",2<u);u=Math.max(L,E);g.Br(t.element,"ytp-videowall-still-round-large",256<=u);g.Br(t.element,"ytp-videowall-still-round-medium",96<u&&256>u);g.Br(t.element,"ytp-videowall-still-round-small",96>=u);q=e[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.W(),y=g.ir(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",l6(t,q,y),g.nN(u)&&!t.api.N("web_player_log_click_before_generating_ve_conversion_params")&&
(u=q.Pk(),y={},g.QP(t.api,"addEmbedsConversionTrackingParams",[y]),u=g.gk(u,g.XI(y,"emb_rel_end")),t.updateValue("url",u)),(q=(q=q.sessionData)&&q.itct)&&t.api.fg(t.element,q));h++}f.ariaBusy="false";g.Br(this.element,"ytp-endscreen-paginate",h<c);for(e=this.stills.length-1;e>=h;e--)a=this.stills[e],g.ef(a.element),g.ob(a);this.stills.length=h}};
g.k.onVideoDataChange=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.C=0,this.videoData=a,this.Yp())};
g.k.y0=function(){this.C+=this.stills.length;this.Yp()};
g.k.z0=function(){this.C-=this.stills.length;this.Yp()};
g.k.HW=function(){return this.j.Sk()};
g.k.sK=function(a){1===a?(this.G=!1,this.D=this.videoData.clientPlaybackNonce,this.j.Or(),this.Hb&&this.Yp()):(this.G=!0,this.Hb&&x6(this)&&(2===a?this.j.aB():3===a&&this.j.Bw()))};
g.k.x0=function(a){if(a){for(a=0;a<this.stills.length;a++)this.J.Ya(this.stills[a].element,!0);this.sK(1)}else this.D=null,this.G=!1;this.Yp()};
g.k.Cf=function(){return this.Hb&&x6(this)};g.x(z6,p6);z6.prototype.show=function(){if(3!==this.player.getPlayerState()){p6.prototype.show.call(this);var a=this.B;if(a){var b=0<this.j.suggestionData.length;g.Br(this.element,"ytp-shorts-branded-ui",b);b?a.show():a.hide()}var c;null==(c=g.SP(this.player))||c.XE(!0);this.player.Ya(this.element,!0);this.watchButton.lc(!0)}};
z6.prototype.hide=function(){p6.prototype.hide.call(this);var a;null==(a=g.SP(this.player))||a.XE(!1);this.player.Ya(this.element,!1);this.watchButton.lc(!1)};g.x(Flb,g.CR);g.k=Flb.prototype;g.k.Pw=function(){var a=this.player.getVideoData(),b=a.mutedAutoplay;if((g.gQ(this.player)||this.B)&&!b)return!0;var c;var d=!!((null==a?0:g.dP(a))||(null==a?0:null==(c=a.suggestions)?0:c.length));d=!Clb(this.player)||d;a=a.tj||g.vN(a.La);c=this.player.JC();return d&&!a&&!c&&!b};
g.k.Cf=function(){return this.endScreen.Cf()};
g.k.K5=function(){return this.Cf()?this.endScreen.HW():!1};
g.k.ya=function(){this.player.mf("endscreen");g.CR.prototype.ya.call(this)};
g.k.load=function(){var a=this.player.getVideoData();var b=a.transitionEndpointAtEndOfStream;if(b&&b.videoId){var c=this.player.Gb().Te.get("heartbeat"),d=g.dP(a);!d||b.videoId!==d.videoId||a.PR?(this.player.Ao(b.videoId,void 0,void 0,!0,!0,b),c&&c.VH("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.CR.prototype.load.call(this),this.endScreen.show())};
g.k.unload=function(){g.CR.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.k.onCueRangeEnter=function(a){this.Pw()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.k.onCueRangeExit=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.k.onVideoDataChange=function(){Elb(this);this.D&&Dlb(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.j?this.endScreen=new r6(this.player):this.endScreen=new w6(this.player),g.H(this,this.endScreen),g.jQ(this.player,this.endScreen.element,4))};g.BR("endscreen",Flb);})(_yt_player);
